// THIS CORNFILE IS GENERATED. DO NOT EDIT! 🌽
#ifndef __AUTHENTICATION_TYPEH
#define __AUTHENTICATION_TYPEH
enum class AuthenticationType {
AUTHENTICATION_USER_PASS = 0,
AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS = 1,
AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS = 2,
AUTHENTICATION_SPOTIFY_TOKEN = 3,
AUTHENTICATION_FACEBOOK_TOKEN = 4,
};

#endif
