// THIS CORNFILE IS GENERATED. DO NOT EDIT! 🌽
#ifndef __OSH
#define __OSH
enum class Os {
OS_UNKNOWN = 0,
OS_WINDOWS = 1,
OS_OSX = 2,
OS_IPHONE = 3,
OS_S60 = 4,
OS_LINUX = 5,
OS_WINDOWS_CE = 6,
OS_ANDROID = 7,
OS_PALM = 8,
OS_FREEBSD = 9,
OS_BLACKBERRY = 10,
OS_SONOS = 11,
OS_LOGITECH = 12,
OS_WP7 = 13,
OS_ONKYO = 14,
OS_PHILIPS = 15,
OS_WD = 16,
OS_VOLVO = 17,
OS_TIVO = 18,
OS_AWOX = 19,
OS_MEEGO = 20,
OS_QNXNTO = 21,
OS_BCO = 22,
};

#endif
