// THIS CORNFILE IS GENERATED. DO NOT EDIT! 🌽
#ifndef __PRODUCTH
#define __PRODUCTH
enum class Product {
PRODUCT_CLIENT = 0,
PRODUCT_LIBSPOTIFY = 1,
PRODUCT_MOBILE = 2,
PRODUCT_PARTNER = 3,
PRODUCT_LIBSPOTIFY_EMBEDDED = 5,
};

#endif
