/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "appstore.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AppInfo, AppInfo, AUTO)


PB_BIND(AppInfoList, AppInfoList, AUTO)


PB_BIND(SemanticVersion, SemanticVersion, AUTO)


PB_BIND(RequestHeader, RequestHeader, AUTO)


PB_BIND(AppItem, AppItem, AUTO)


PB_BIND(AppList, AppList, AUTO)


PB_BIND(IdentifierList, IdentifierList, AUTO)


PB_BIND(BannerConfig, BannerConfig, AUTO)







