/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_APPSTORE_PB_H_INCLUDED
#define PB_APPSTORE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _RequestHeader_Platform {
    RequestHeader_Platform_WIN32_X86 = 0,
    RequestHeader_Platform_OSX_X86 = 1,
    RequestHeader_Platform_LINUX_X86 = 2,
    RequestHeader_Platform_IPHONE_ARM = 3,
    RequestHeader_Platform_SYMBIANS60_ARM = 4,
    RequestHeader_Platform_OSX_POWERPC = 5,
    RequestHeader_Platform_ANDROID_ARM = 6,
    RequestHeader_Platform_WINCE_ARM = 7,
    RequestHeader_Platform_LINUX_X86_64 = 8,
    RequestHeader_Platform_OSX_X86_64 = 9,
    RequestHeader_Platform_PALM_ARM = 10,
    RequestHeader_Platform_LINUX_SH = 11,
    RequestHeader_Platform_FREEBSD_X86 = 12,
    RequestHeader_Platform_FREEBSD_X86_64 = 13,
    RequestHeader_Platform_BLACKBERRY_ARM = 14,
    RequestHeader_Platform_SONOS_UNKNOWN = 15,
    RequestHeader_Platform_LINUX_MIPS = 16,
    RequestHeader_Platform_LINUX_ARM = 17,
    RequestHeader_Platform_LOGITECH_ARM = 18,
    RequestHeader_Platform_LINUX_BLACKFIN = 19,
    RequestHeader_Platform_ONKYO_ARM = 21,
    RequestHeader_Platform_QNXNTO_ARM = 22,
    RequestHeader_Platform_BADPLATFORM = 255
} RequestHeader_Platform;

typedef enum _RequestHeader_DeviceClass {
    RequestHeader_DeviceClass_DESKTOP = 1,
    RequestHeader_DeviceClass_TABLET = 2,
    RequestHeader_DeviceClass_MOBILE = 3,
    RequestHeader_DeviceClass_WEB = 4,
    RequestHeader_DeviceClass_TV = 5
} RequestHeader_DeviceClass;

typedef enum _AppItem_Requirement {
    AppItem_Requirement_REQUIRED_INSTALL = 1,
    AppItem_Requirement_LAZYLOAD = 2,
    AppItem_Requirement_OPTIONAL_INSTALL = 3
} AppItem_Requirement;

typedef enum _AppItem_Type {
    AppItem_Type_APPLICATION = 0,
    AppItem_Type_FRAMEWORK = 1,
    AppItem_Type_BRIDGE = 2
} AppItem_Type;

/* Struct definitions */
typedef struct _AppInfoList {
    pb_callback_t items;
} AppInfoList;

typedef struct _AppList {
    pb_callback_t items;
} AppList;

typedef struct _BannerConfig {
    pb_callback_t json;
} BannerConfig;

typedef struct _IdentifierList {
    pb_callback_t identifiers;
} IdentifierList;

typedef struct _AppInfo {
    pb_callback_t identifier;
    bool has_version_int;
    int32_t version_int;
} AppInfo;

typedef struct _SemanticVersion {
    bool has_major;
    int32_t major;
    bool has_minor;
    int32_t minor;
    bool has_patch;
    int32_t patch;
} SemanticVersion;

typedef struct _AppItem {
    pb_callback_t identifier;
    bool has_requirement;
    AppItem_Requirement requirement;
    pb_callback_t manifest;
    pb_callback_t checksum;
    pb_callback_t bundle_uri;
    pb_callback_t small_icon_uri;
    pb_callback_t large_icon_uri;
    pb_callback_t medium_icon_uri;
    bool has_bundle_type;
    AppItem_Type bundle_type;
    bool has_version;
    SemanticVersion version;
    bool has_ttl_in_seconds;
    uint32_t ttl_in_seconds;
    bool has_categories;
    IdentifierList categories;
} AppItem;

typedef struct _RequestHeader {
    pb_callback_t market;
    bool has_platform;
    RequestHeader_Platform platform;
    bool has_app_infos;
    AppInfoList app_infos;
    pb_callback_t bridge_identifier;
    bool has_bridge_version;
    SemanticVersion bridge_version;
    bool has_device_class;
    RequestHeader_DeviceClass device_class;
} RequestHeader;


/* Helper constants for enums */
#define _RequestHeader_Platform_MIN RequestHeader_Platform_WIN32_X86
#define _RequestHeader_Platform_MAX RequestHeader_Platform_BADPLATFORM
#define _RequestHeader_Platform_ARRAYSIZE ((RequestHeader_Platform)(RequestHeader_Platform_BADPLATFORM+1))

#define _RequestHeader_DeviceClass_MIN RequestHeader_DeviceClass_DESKTOP
#define _RequestHeader_DeviceClass_MAX RequestHeader_DeviceClass_TV
#define _RequestHeader_DeviceClass_ARRAYSIZE ((RequestHeader_DeviceClass)(RequestHeader_DeviceClass_TV+1))

#define _AppItem_Requirement_MIN AppItem_Requirement_REQUIRED_INSTALL
#define _AppItem_Requirement_MAX AppItem_Requirement_OPTIONAL_INSTALL
#define _AppItem_Requirement_ARRAYSIZE ((AppItem_Requirement)(AppItem_Requirement_OPTIONAL_INSTALL+1))

#define _AppItem_Type_MIN AppItem_Type_APPLICATION
#define _AppItem_Type_MAX AppItem_Type_BRIDGE
#define _AppItem_Type_ARRAYSIZE ((AppItem_Type)(AppItem_Type_BRIDGE+1))


/* Initializer values for message structs */
#define AppInfo_init_default                     {{{NULL}, NULL}, false, 0}
#define AppInfoList_init_default                 {{{NULL}, NULL}}
#define SemanticVersion_init_default             {false, 0, false, 0, false, 0}
#define RequestHeader_init_default               {{{NULL}, NULL}, false, _RequestHeader_Platform_MIN, false, AppInfoList_init_default, {{NULL}, NULL}, false, SemanticVersion_init_default, false, _RequestHeader_DeviceClass_MIN}
#define AppItem_init_default                     {{{NULL}, NULL}, false, _AppItem_Requirement_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _AppItem_Type_MIN, false, SemanticVersion_init_default, false, 0, false, IdentifierList_init_default}
#define AppList_init_default                     {{{NULL}, NULL}}
#define IdentifierList_init_default              {{{NULL}, NULL}}
#define BannerConfig_init_default                {{{NULL}, NULL}}
#define AppInfo_init_zero                        {{{NULL}, NULL}, false, 0}
#define AppInfoList_init_zero                    {{{NULL}, NULL}}
#define SemanticVersion_init_zero                {false, 0, false, 0, false, 0}
#define RequestHeader_init_zero                  {{{NULL}, NULL}, false, _RequestHeader_Platform_MIN, false, AppInfoList_init_zero, {{NULL}, NULL}, false, SemanticVersion_init_zero, false, _RequestHeader_DeviceClass_MIN}
#define AppItem_init_zero                        {{{NULL}, NULL}, false, _AppItem_Requirement_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _AppItem_Type_MIN, false, SemanticVersion_init_zero, false, 0, false, IdentifierList_init_zero}
#define AppList_init_zero                        {{{NULL}, NULL}}
#define IdentifierList_init_zero                 {{{NULL}, NULL}}
#define BannerConfig_init_zero                   {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define AppInfoList_items_tag                    1
#define AppList_items_tag                        1
#define BannerConfig_json_tag                    1
#define IdentifierList_identifiers_tag           1
#define AppInfo_identifier_tag                   1
#define AppInfo_version_int_tag                  2
#define SemanticVersion_major_tag                1
#define SemanticVersion_minor_tag                2
#define SemanticVersion_patch_tag                3
#define AppItem_identifier_tag                   1
#define AppItem_requirement_tag                  2
#define AppItem_manifest_tag                     4
#define AppItem_checksum_tag                     5
#define AppItem_bundle_uri_tag                   6
#define AppItem_small_icon_uri_tag               7
#define AppItem_large_icon_uri_tag               8
#define AppItem_medium_icon_uri_tag              9
#define AppItem_bundle_type_tag                  10
#define AppItem_version_tag                      11
#define AppItem_ttl_in_seconds_tag               12
#define AppItem_categories_tag                   13
#define RequestHeader_market_tag                 1
#define RequestHeader_platform_tag               2
#define RequestHeader_app_infos_tag              6
#define RequestHeader_bridge_identifier_tag      7
#define RequestHeader_bridge_version_tag         8
#define RequestHeader_device_class_tag           9

/* Struct field encoding specification for nanopb */
#define AppInfo_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   identifier,        1) \
X(a, STATIC,   OPTIONAL, INT32,    version_int,       2)
#define AppInfo_CALLBACK pb_default_field_callback
#define AppInfo_DEFAULT NULL

#define AppInfoList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             1)
#define AppInfoList_CALLBACK pb_default_field_callback
#define AppInfoList_DEFAULT NULL
#define AppInfoList_items_MSGTYPE AppInfo

#define SemanticVersion_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    major,             1) \
X(a, STATIC,   OPTIONAL, INT32,    minor,             2) \
X(a, STATIC,   OPTIONAL, INT32,    patch,             3)
#define SemanticVersion_CALLBACK NULL
#define SemanticVersion_DEFAULT NULL

#define RequestHeader_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   market,            1) \
X(a, STATIC,   OPTIONAL, UENUM,    platform,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  app_infos,         6) \
X(a, CALLBACK, OPTIONAL, STRING,   bridge_identifier,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bridge_version,    8) \
X(a, STATIC,   OPTIONAL, UENUM,    device_class,      9)
#define RequestHeader_CALLBACK pb_default_field_callback
#define RequestHeader_DEFAULT (const pb_byte_t*)"\x48\x01\x00"
#define RequestHeader_app_infos_MSGTYPE AppInfoList
#define RequestHeader_bridge_version_MSGTYPE SemanticVersion

#define AppItem_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   identifier,        1) \
X(a, STATIC,   OPTIONAL, UENUM,    requirement,       2) \
X(a, CALLBACK, OPTIONAL, STRING,   manifest,          4) \
X(a, CALLBACK, OPTIONAL, STRING,   checksum,          5) \
X(a, CALLBACK, OPTIONAL, STRING,   bundle_uri,        6) \
X(a, CALLBACK, OPTIONAL, STRING,   small_icon_uri,    7) \
X(a, CALLBACK, OPTIONAL, STRING,   large_icon_uri,    8) \
X(a, CALLBACK, OPTIONAL, STRING,   medium_icon_uri,   9) \
X(a, STATIC,   OPTIONAL, UENUM,    bundle_type,      10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,          11) \
X(a, STATIC,   OPTIONAL, UINT32,   ttl_in_seconds,   12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  categories,       13)
#define AppItem_CALLBACK pb_default_field_callback
#define AppItem_DEFAULT (const pb_byte_t*)"\x10\x01\x00"
#define AppItem_version_MSGTYPE SemanticVersion
#define AppItem_categories_MSGTYPE IdentifierList

#define AppList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             1)
#define AppList_CALLBACK pb_default_field_callback
#define AppList_DEFAULT NULL
#define AppList_items_MSGTYPE AppItem

#define IdentifierList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   identifiers,       1)
#define IdentifierList_CALLBACK pb_default_field_callback
#define IdentifierList_DEFAULT NULL

#define BannerConfig_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   json,              1)
#define BannerConfig_CALLBACK pb_default_field_callback
#define BannerConfig_DEFAULT NULL

extern const pb_msgdesc_t AppInfo_msg;
extern const pb_msgdesc_t AppInfoList_msg;
extern const pb_msgdesc_t SemanticVersion_msg;
extern const pb_msgdesc_t RequestHeader_msg;
extern const pb_msgdesc_t AppItem_msg;
extern const pb_msgdesc_t AppList_msg;
extern const pb_msgdesc_t IdentifierList_msg;
extern const pb_msgdesc_t BannerConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AppInfo_fields &AppInfo_msg
#define AppInfoList_fields &AppInfoList_msg
#define SemanticVersion_fields &SemanticVersion_msg
#define RequestHeader_fields &RequestHeader_msg
#define AppItem_fields &AppItem_msg
#define AppList_fields &AppList_msg
#define IdentifierList_fields &IdentifierList_msg
#define BannerConfig_fields &BannerConfig_msg

/* Maximum encoded size of messages (where known) */
/* AppInfo_size depends on runtime parameters */
/* AppInfoList_size depends on runtime parameters */
#define SemanticVersion_size                     33
/* RequestHeader_size depends on runtime parameters */
/* AppItem_size depends on runtime parameters */
/* AppList_size depends on runtime parameters */
/* IdentifierList_size depends on runtime parameters */
/* BannerConfig_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
