/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "facebook-publish.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EventReply, EventReply, AUTO)


PB_BIND(RetryInfo, RetryInfo, AUTO)


PB_BIND(Id, Id, AUTO)


PB_BIND(Start, Start, AUTO)


PB_BIND(Seek, Seek, AUTO)


PB_BIND(Pause, Pause, AUTO)


PB_BIND(Resume, Resume, AUTO)


PB_BIND(End, End, AUTO)


PB_BIND(Event, Event, AUTO)



