/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_FACEBOOK_PB_H_INCLUDED
#define PB_FACEBOOK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AuthConfig {
    pb_callback_t url;
    pb_callback_t permissions;
    pb_callback_t blacklist;
    pb_callback_t whitelist;
    pb_callback_t cancel;
} AuthConfig;

typedef struct _Credential {
    pb_callback_t facebook_uid;
    pb_callback_t access_token;
} Credential;

typedef struct _GrantPermissionsReply {
    pb_callback_t granted;
    pb_callback_t failed;
} GrantPermissionsReply;

typedef struct _InboxReply {
    pb_callback_t message_id;
    pb_callback_t thread_id;
} InboxReply;

typedef struct _OpenGraphError {
    pb_callback_t permanent;
    pb_callback_t invalid_token;
    pb_callback_t retries;
} OpenGraphError;

typedef struct _PermissionsReply {
    pb_callback_t permissions;
} PermissionsReply;

typedef struct _ShareReply {
    pb_callback_t post_id;
} ShareReply;

typedef struct _DisableRequest {
    bool has_credential;
    Credential credential;
} DisableRequest;

typedef struct _EnableReply {
    bool has_credential;
    Credential credential;
} EnableReply;

typedef struct _EnableRequest {
    bool has_credential;
    Credential credential;
} EnableRequest;

typedef struct _FriendsFields {
    bool has_app_user;
    bool app_user;
    bool has_display_name;
    bool display_name;
    bool has_picture_large;
    bool picture_large;
} FriendsFields;

typedef struct _FriendsOptions {
    bool has_limit;
    int32_t limit;
    bool has_offset;
    int32_t offset;
    bool has_cache_is_king;
    bool cache_is_king;
    bool has_app_friends;
    bool app_friends;
    bool has_non_app_friends;
    bool non_app_friends;
} FriendsOptions;

typedef struct _FriendsReply {
    pb_callback_t friends;
    bool has_more;
    bool more;
} FriendsReply;

typedef struct _GrantPermissionsRequest {
    bool has_credential;
    Credential credential;
    pb_callback_t permissions;
} GrantPermissionsRequest;

typedef struct _InboxRequest {
    bool has_credential;
    Credential credential;
    pb_callback_t facebook_uids;
    pb_callback_t message_text;
    pb_callback_t message_link;
} InboxRequest;

typedef struct _InspectCredentialReply {
    bool has_alternative_credential;
    Credential alternative_credential;
    bool has_app_user;
    bool app_user;
    bool has_permanent_error;
    bool permanent_error;
    bool has_transient_error;
    bool transient_error;
} InspectCredentialReply;

typedef struct _InspectCredentialRequest {
    bool has_credential;
    Credential credential;
} InspectCredentialRequest;

typedef struct _OpenGraphScrobble {
    bool has_create_delay;
    int32_t create_delay;
} OpenGraphScrobble;

typedef struct _PermissionsOptions {
    bool has_cache_is_king;
    bool cache_is_king;
} PermissionsOptions;

typedef struct _RevokeRequest {
    bool has_credential;
    Credential credential;
} RevokeRequest;

typedef struct _ShareRequest {
    bool has_credential;
    Credential credential;
    pb_callback_t uri;
    pb_callback_t message_text;
} ShareRequest;

typedef struct _TransferRequest {
    bool has_credential;
    Credential credential;
    pb_callback_t source_username;
    pb_callback_t target_username;
} TransferRequest;

typedef struct _UpdateUserStateRequest {
    bool has_credential;
    Credential credential;
} UpdateUserStateRequest;

typedef struct _User {
    pb_callback_t spotify_username;
    pb_callback_t facebook_uid;
    bool has_app_user;
    bool app_user;
    pb_callback_t display_name;
    pb_callback_t first_name;
    pb_callback_t middle_name;
    pb_callback_t last_name;
    pb_callback_t picture_large;
    pb_callback_t picture_square;
    pb_callback_t gender;
    pb_callback_t email;
} User;

typedef struct _UserFields {
    bool has_app_user;
    bool app_user;
    bool has_display_name;
    bool display_name;
    bool has_first_name;
    bool first_name;
    bool has_middle_name;
    bool middle_name;
    bool has_last_name;
    bool last_name;
    bool has_picture_large;
    bool picture_large;
    bool has_picture_square;
    bool picture_square;
    bool has_gender;
    bool gender;
    bool has_email;
    bool email;
} UserFields;

typedef struct _UserOptions {
    bool has_cache_is_king;
    bool cache_is_king;
} UserOptions;

typedef struct _UserState {
    bool has_credential;
    Credential credential;
} UserState;

typedef struct _FriendsRequest {
    bool has_options;
    FriendsOptions options;
    bool has_fields;
    FriendsFields fields;
} FriendsRequest;

typedef struct _OpenGraphConfig {
    bool has_error;
    OpenGraphError error;
    bool has_scrobble;
    OpenGraphScrobble scrobble;
} OpenGraphConfig;

typedef struct _PermissionsRequest {
    bool has_credential;
    Credential credential;
    bool has_options;
    PermissionsOptions options;
} PermissionsRequest;

typedef struct _UserRequest {
    bool has_options;
    UserOptions options;
    bool has_fields;
    UserFields fields;
} UserRequest;

typedef struct _ConfigReply {
    pb_callback_t domain;
    pb_callback_t app_id;
    pb_callback_t app_namespace;
    bool has_auth;
    AuthConfig auth;
    bool has_og;
    OpenGraphConfig og;
} ConfigReply;


/* Initializer values for message structs */
#define Credential_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}}
#define EnableRequest_init_default               {false, Credential_init_default}
#define EnableReply_init_default                 {false, Credential_init_default}
#define DisableRequest_init_default              {false, Credential_init_default}
#define RevokeRequest_init_default               {false, Credential_init_default}
#define InspectCredentialRequest_init_default    {false, Credential_init_default}
#define InspectCredentialReply_init_default      {false, Credential_init_default, false, 0, false, 0, false, 0}
#define UserState_init_default                   {false, Credential_init_default}
#define UpdateUserStateRequest_init_default      {false, Credential_init_default}
#define OpenGraphError_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define OpenGraphScrobble_init_default           {false, 0}
#define OpenGraphConfig_init_default             {false, OpenGraphError_init_default, false, OpenGraphScrobble_init_default}
#define AuthConfig_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ConfigReply_init_default                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, AuthConfig_init_default, false, OpenGraphConfig_init_default}
#define UserFields_init_default                  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define UserOptions_init_default                 {false, 0}
#define UserRequest_init_default                 {false, UserOptions_init_default, false, UserFields_init_default}
#define User_init_default                        {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define FriendsFields_init_default               {false, 0, false, 0, false, 0}
#define FriendsOptions_init_default              {false, 0, false, 0, false, 0, false, 0, false, 0}
#define FriendsRequest_init_default              {false, FriendsOptions_init_default, false, FriendsFields_init_default}
#define FriendsReply_init_default                {{{NULL}, NULL}, false, 0}
#define ShareRequest_init_default                {false, Credential_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define ShareReply_init_default                  {{{NULL}, NULL}}
#define InboxRequest_init_default                {false, Credential_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define InboxReply_init_default                  {{{NULL}, NULL}, {{NULL}, NULL}}
#define PermissionsOptions_init_default          {false, 0}
#define PermissionsRequest_init_default          {false, Credential_init_default, false, PermissionsOptions_init_default}
#define PermissionsReply_init_default            {{{NULL}, NULL}}
#define GrantPermissionsRequest_init_default     {false, Credential_init_default, {{NULL}, NULL}}
#define GrantPermissionsReply_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define TransferRequest_init_default             {false, Credential_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define Credential_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}}
#define EnableRequest_init_zero                  {false, Credential_init_zero}
#define EnableReply_init_zero                    {false, Credential_init_zero}
#define DisableRequest_init_zero                 {false, Credential_init_zero}
#define RevokeRequest_init_zero                  {false, Credential_init_zero}
#define InspectCredentialRequest_init_zero       {false, Credential_init_zero}
#define InspectCredentialReply_init_zero         {false, Credential_init_zero, false, 0, false, 0, false, 0}
#define UserState_init_zero                      {false, Credential_init_zero}
#define UpdateUserStateRequest_init_zero         {false, Credential_init_zero}
#define OpenGraphError_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define OpenGraphScrobble_init_zero              {false, 0}
#define OpenGraphConfig_init_zero                {false, OpenGraphError_init_zero, false, OpenGraphScrobble_init_zero}
#define AuthConfig_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ConfigReply_init_zero                    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, AuthConfig_init_zero, false, OpenGraphConfig_init_zero}
#define UserFields_init_zero                     {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define UserOptions_init_zero                    {false, 0}
#define UserRequest_init_zero                    {false, UserOptions_init_zero, false, UserFields_init_zero}
#define User_init_zero                           {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define FriendsFields_init_zero                  {false, 0, false, 0, false, 0}
#define FriendsOptions_init_zero                 {false, 0, false, 0, false, 0, false, 0, false, 0}
#define FriendsRequest_init_zero                 {false, FriendsOptions_init_zero, false, FriendsFields_init_zero}
#define FriendsReply_init_zero                   {{{NULL}, NULL}, false, 0}
#define ShareRequest_init_zero                   {false, Credential_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define ShareReply_init_zero                     {{{NULL}, NULL}}
#define InboxRequest_init_zero                   {false, Credential_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define InboxReply_init_zero                     {{{NULL}, NULL}, {{NULL}, NULL}}
#define PermissionsOptions_init_zero             {false, 0}
#define PermissionsRequest_init_zero             {false, Credential_init_zero, false, PermissionsOptions_init_zero}
#define PermissionsReply_init_zero               {{{NULL}, NULL}}
#define GrantPermissionsRequest_init_zero        {false, Credential_init_zero, {{NULL}, NULL}}
#define GrantPermissionsReply_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define TransferRequest_init_zero                {false, Credential_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define AuthConfig_url_tag                       1
#define AuthConfig_permissions_tag               2
#define AuthConfig_blacklist_tag                 3
#define AuthConfig_whitelist_tag                 4
#define AuthConfig_cancel_tag                    5
#define Credential_facebook_uid_tag              1
#define Credential_access_token_tag              2
#define GrantPermissionsReply_granted_tag        1
#define GrantPermissionsReply_failed_tag         2
#define InboxReply_message_id_tag                1
#define InboxReply_thread_id_tag                 2
#define OpenGraphError_permanent_tag             1
#define OpenGraphError_invalid_token_tag         2
#define OpenGraphError_retries_tag               3
#define PermissionsReply_permissions_tag         1
#define ShareReply_post_id_tag                   1
#define DisableRequest_credential_tag            1
#define EnableReply_credential_tag               1
#define EnableRequest_credential_tag             1
#define FriendsFields_app_user_tag               1
#define FriendsFields_display_name_tag           2
#define FriendsFields_picture_large_tag          6
#define FriendsOptions_limit_tag                 1
#define FriendsOptions_offset_tag                2
#define FriendsOptions_cache_is_king_tag         3
#define FriendsOptions_app_friends_tag           4
#define FriendsOptions_non_app_friends_tag       5
#define FriendsReply_friends_tag                 1
#define FriendsReply_more_tag                    2
#define GrantPermissionsRequest_credential_tag   1
#define GrantPermissionsRequest_permissions_tag  2
#define InboxRequest_credential_tag              1
#define InboxRequest_facebook_uids_tag           3
#define InboxRequest_message_text_tag            4
#define InboxRequest_message_link_tag            5
#define InspectCredentialReply_alternative_credential_tag 1
#define InspectCredentialReply_app_user_tag      2
#define InspectCredentialReply_permanent_error_tag 3
#define InspectCredentialReply_transient_error_tag 4
#define InspectCredentialRequest_credential_tag  1
#define OpenGraphScrobble_create_delay_tag       1
#define PermissionsOptions_cache_is_king_tag     1
#define RevokeRequest_credential_tag             1
#define ShareRequest_credential_tag              1
#define ShareRequest_uri_tag                     2
#define ShareRequest_message_text_tag            3
#define TransferRequest_credential_tag           1
#define TransferRequest_source_username_tag      2
#define TransferRequest_target_username_tag      3
#define UpdateUserStateRequest_credential_tag    1
#define User_spotify_username_tag                1
#define User_facebook_uid_tag                    2
#define User_app_user_tag                        3
#define User_display_name_tag                    4
#define User_first_name_tag                      5
#define User_middle_name_tag                     6
#define User_last_name_tag                       7
#define User_picture_large_tag                   8
#define User_picture_square_tag                  9
#define User_gender_tag                          10
#define User_email_tag                           11
#define UserFields_app_user_tag                  1
#define UserFields_display_name_tag              2
#define UserFields_first_name_tag                3
#define UserFields_middle_name_tag               4
#define UserFields_last_name_tag                 5
#define UserFields_picture_large_tag             6
#define UserFields_picture_square_tag            7
#define UserFields_gender_tag                    8
#define UserFields_email_tag                     9
#define UserOptions_cache_is_king_tag            1
#define UserState_credential_tag                 1
#define FriendsRequest_options_tag               1
#define FriendsRequest_fields_tag                2
#define OpenGraphConfig_error_tag                1
#define OpenGraphConfig_scrobble_tag             2
#define PermissionsRequest_credential_tag        1
#define PermissionsRequest_options_tag           2
#define UserRequest_options_tag                  1
#define UserRequest_fields_tag                   2
#define ConfigReply_domain_tag                   1
#define ConfigReply_app_id_tag                   2
#define ConfigReply_app_namespace_tag            3
#define ConfigReply_auth_tag                     4
#define ConfigReply_og_tag                       5

/* Struct field encoding specification for nanopb */
#define Credential_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   facebook_uid,      1) \
X(a, CALLBACK, OPTIONAL, STRING,   access_token,      2)
#define Credential_CALLBACK pb_default_field_callback
#define Credential_DEFAULT NULL

#define EnableRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1)
#define EnableRequest_CALLBACK NULL
#define EnableRequest_DEFAULT NULL
#define EnableRequest_credential_MSGTYPE Credential

#define EnableReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1)
#define EnableReply_CALLBACK NULL
#define EnableReply_DEFAULT NULL
#define EnableReply_credential_MSGTYPE Credential

#define DisableRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1)
#define DisableRequest_CALLBACK NULL
#define DisableRequest_DEFAULT NULL
#define DisableRequest_credential_MSGTYPE Credential

#define RevokeRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1)
#define RevokeRequest_CALLBACK NULL
#define RevokeRequest_DEFAULT NULL
#define RevokeRequest_credential_MSGTYPE Credential

#define InspectCredentialRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1)
#define InspectCredentialRequest_CALLBACK NULL
#define InspectCredentialRequest_DEFAULT NULL
#define InspectCredentialRequest_credential_MSGTYPE Credential

#define InspectCredentialReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  alternative_credential,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     app_user,          2) \
X(a, STATIC,   OPTIONAL, BOOL,     permanent_error,   3) \
X(a, STATIC,   OPTIONAL, BOOL,     transient_error,   4)
#define InspectCredentialReply_CALLBACK NULL
#define InspectCredentialReply_DEFAULT NULL
#define InspectCredentialReply_alternative_credential_MSGTYPE Credential

#define UserState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1)
#define UserState_CALLBACK NULL
#define UserState_DEFAULT NULL
#define UserState_credential_MSGTYPE Credential

#define UpdateUserStateRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1)
#define UpdateUserStateRequest_CALLBACK NULL
#define UpdateUserStateRequest_DEFAULT NULL
#define UpdateUserStateRequest_credential_MSGTYPE Credential

#define OpenGraphError_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   permanent,         1) \
X(a, CALLBACK, REPEATED, STRING,   invalid_token,     2) \
X(a, CALLBACK, REPEATED, STRING,   retries,           3)
#define OpenGraphError_CALLBACK pb_default_field_callback
#define OpenGraphError_DEFAULT NULL

#define OpenGraphScrobble_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    create_delay,      1)
#define OpenGraphScrobble_CALLBACK NULL
#define OpenGraphScrobble_DEFAULT NULL

#define OpenGraphConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  error,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scrobble,          2)
#define OpenGraphConfig_CALLBACK NULL
#define OpenGraphConfig_DEFAULT NULL
#define OpenGraphConfig_error_MSGTYPE OpenGraphError
#define OpenGraphConfig_scrobble_MSGTYPE OpenGraphScrobble

#define AuthConfig_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   url,               1) \
X(a, CALLBACK, REPEATED, STRING,   permissions,       2) \
X(a, CALLBACK, REPEATED, STRING,   blacklist,         3) \
X(a, CALLBACK, REPEATED, STRING,   whitelist,         4) \
X(a, CALLBACK, REPEATED, STRING,   cancel,            5)
#define AuthConfig_CALLBACK pb_default_field_callback
#define AuthConfig_DEFAULT NULL

#define ConfigReply_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   domain,            1) \
X(a, CALLBACK, OPTIONAL, STRING,   app_id,            2) \
X(a, CALLBACK, OPTIONAL, STRING,   app_namespace,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  auth,              4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  og,                5)
#define ConfigReply_CALLBACK pb_default_field_callback
#define ConfigReply_DEFAULT NULL
#define ConfigReply_auth_MSGTYPE AuthConfig
#define ConfigReply_og_MSGTYPE OpenGraphConfig

#define UserFields_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     app_user,          1) \
X(a, STATIC,   OPTIONAL, BOOL,     display_name,      2) \
X(a, STATIC,   OPTIONAL, BOOL,     first_name,        3) \
X(a, STATIC,   OPTIONAL, BOOL,     middle_name,       4) \
X(a, STATIC,   OPTIONAL, BOOL,     last_name,         5) \
X(a, STATIC,   OPTIONAL, BOOL,     picture_large,     6) \
X(a, STATIC,   OPTIONAL, BOOL,     picture_square,    7) \
X(a, STATIC,   OPTIONAL, BOOL,     gender,            8) \
X(a, STATIC,   OPTIONAL, BOOL,     email,             9)
#define UserFields_CALLBACK NULL
#define UserFields_DEFAULT NULL

#define UserOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     cache_is_king,     1)
#define UserOptions_CALLBACK NULL
#define UserOptions_DEFAULT NULL

#define UserRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fields,            2)
#define UserRequest_CALLBACK NULL
#define UserRequest_DEFAULT NULL
#define UserRequest_options_MSGTYPE UserOptions
#define UserRequest_fields_MSGTYPE UserFields

#define User_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   spotify_username,   1) \
X(a, CALLBACK, OPTIONAL, STRING,   facebook_uid,      2) \
X(a, STATIC,   OPTIONAL, BOOL,     app_user,          3) \
X(a, CALLBACK, OPTIONAL, STRING,   display_name,      4) \
X(a, CALLBACK, OPTIONAL, STRING,   first_name,        5) \
X(a, CALLBACK, OPTIONAL, STRING,   middle_name,       6) \
X(a, CALLBACK, OPTIONAL, STRING,   last_name,         7) \
X(a, CALLBACK, OPTIONAL, STRING,   picture_large,     8) \
X(a, CALLBACK, OPTIONAL, STRING,   picture_square,    9) \
X(a, CALLBACK, OPTIONAL, STRING,   gender,           10) \
X(a, CALLBACK, OPTIONAL, STRING,   email,            11)
#define User_CALLBACK pb_default_field_callback
#define User_DEFAULT NULL

#define FriendsFields_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     app_user,          1) \
X(a, STATIC,   OPTIONAL, BOOL,     display_name,      2) \
X(a, STATIC,   OPTIONAL, BOOL,     picture_large,     6)
#define FriendsFields_CALLBACK NULL
#define FriendsFields_DEFAULT NULL

#define FriendsOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    limit,             1) \
X(a, STATIC,   OPTIONAL, INT32,    offset,            2) \
X(a, STATIC,   OPTIONAL, BOOL,     cache_is_king,     3) \
X(a, STATIC,   OPTIONAL, BOOL,     app_friends,       4) \
X(a, STATIC,   OPTIONAL, BOOL,     non_app_friends,   5)
#define FriendsOptions_CALLBACK NULL
#define FriendsOptions_DEFAULT NULL

#define FriendsRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fields,            2)
#define FriendsRequest_CALLBACK NULL
#define FriendsRequest_DEFAULT NULL
#define FriendsRequest_options_MSGTYPE FriendsOptions
#define FriendsRequest_fields_MSGTYPE FriendsFields

#define FriendsReply_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  friends,           1) \
X(a, STATIC,   OPTIONAL, BOOL,     more,              2)
#define FriendsReply_CALLBACK pb_default_field_callback
#define FriendsReply_DEFAULT NULL
#define FriendsReply_friends_MSGTYPE User

#define ShareRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               2) \
X(a, CALLBACK, OPTIONAL, STRING,   message_text,      3)
#define ShareRequest_CALLBACK pb_default_field_callback
#define ShareRequest_DEFAULT NULL
#define ShareRequest_credential_MSGTYPE Credential

#define ShareReply_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   post_id,           1)
#define ShareReply_CALLBACK pb_default_field_callback
#define ShareReply_DEFAULT NULL

#define InboxRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1) \
X(a, CALLBACK, REPEATED, STRING,   facebook_uids,     3) \
X(a, CALLBACK, OPTIONAL, STRING,   message_text,      4) \
X(a, CALLBACK, OPTIONAL, STRING,   message_link,      5)
#define InboxRequest_CALLBACK pb_default_field_callback
#define InboxRequest_DEFAULT NULL
#define InboxRequest_credential_MSGTYPE Credential

#define InboxReply_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   message_id,        1) \
X(a, CALLBACK, OPTIONAL, STRING,   thread_id,         2)
#define InboxReply_CALLBACK pb_default_field_callback
#define InboxReply_DEFAULT NULL

#define PermissionsOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     cache_is_king,     1)
#define PermissionsOptions_CALLBACK NULL
#define PermissionsOptions_DEFAULT NULL

#define PermissionsRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  options,           2)
#define PermissionsRequest_CALLBACK NULL
#define PermissionsRequest_DEFAULT NULL
#define PermissionsRequest_credential_MSGTYPE Credential
#define PermissionsRequest_options_MSGTYPE PermissionsOptions

#define PermissionsReply_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   permissions,       1)
#define PermissionsReply_CALLBACK pb_default_field_callback
#define PermissionsReply_DEFAULT NULL

#define GrantPermissionsRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1) \
X(a, CALLBACK, REPEATED, STRING,   permissions,       2)
#define GrantPermissionsRequest_CALLBACK pb_default_field_callback
#define GrantPermissionsRequest_DEFAULT NULL
#define GrantPermissionsRequest_credential_MSGTYPE Credential

#define GrantPermissionsReply_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   granted,           1) \
X(a, CALLBACK, REPEATED, STRING,   failed,            2)
#define GrantPermissionsReply_CALLBACK pb_default_field_callback
#define GrantPermissionsReply_DEFAULT NULL

#define TransferRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  credential,        1) \
X(a, CALLBACK, OPTIONAL, STRING,   source_username,   2) \
X(a, CALLBACK, OPTIONAL, STRING,   target_username,   3)
#define TransferRequest_CALLBACK pb_default_field_callback
#define TransferRequest_DEFAULT NULL
#define TransferRequest_credential_MSGTYPE Credential

extern const pb_msgdesc_t Credential_msg;
extern const pb_msgdesc_t EnableRequest_msg;
extern const pb_msgdesc_t EnableReply_msg;
extern const pb_msgdesc_t DisableRequest_msg;
extern const pb_msgdesc_t RevokeRequest_msg;
extern const pb_msgdesc_t InspectCredentialRequest_msg;
extern const pb_msgdesc_t InspectCredentialReply_msg;
extern const pb_msgdesc_t UserState_msg;
extern const pb_msgdesc_t UpdateUserStateRequest_msg;
extern const pb_msgdesc_t OpenGraphError_msg;
extern const pb_msgdesc_t OpenGraphScrobble_msg;
extern const pb_msgdesc_t OpenGraphConfig_msg;
extern const pb_msgdesc_t AuthConfig_msg;
extern const pb_msgdesc_t ConfigReply_msg;
extern const pb_msgdesc_t UserFields_msg;
extern const pb_msgdesc_t UserOptions_msg;
extern const pb_msgdesc_t UserRequest_msg;
extern const pb_msgdesc_t User_msg;
extern const pb_msgdesc_t FriendsFields_msg;
extern const pb_msgdesc_t FriendsOptions_msg;
extern const pb_msgdesc_t FriendsRequest_msg;
extern const pb_msgdesc_t FriendsReply_msg;
extern const pb_msgdesc_t ShareRequest_msg;
extern const pb_msgdesc_t ShareReply_msg;
extern const pb_msgdesc_t InboxRequest_msg;
extern const pb_msgdesc_t InboxReply_msg;
extern const pb_msgdesc_t PermissionsOptions_msg;
extern const pb_msgdesc_t PermissionsRequest_msg;
extern const pb_msgdesc_t PermissionsReply_msg;
extern const pb_msgdesc_t GrantPermissionsRequest_msg;
extern const pb_msgdesc_t GrantPermissionsReply_msg;
extern const pb_msgdesc_t TransferRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Credential_fields &Credential_msg
#define EnableRequest_fields &EnableRequest_msg
#define EnableReply_fields &EnableReply_msg
#define DisableRequest_fields &DisableRequest_msg
#define RevokeRequest_fields &RevokeRequest_msg
#define InspectCredentialRequest_fields &InspectCredentialRequest_msg
#define InspectCredentialReply_fields &InspectCredentialReply_msg
#define UserState_fields &UserState_msg
#define UpdateUserStateRequest_fields &UpdateUserStateRequest_msg
#define OpenGraphError_fields &OpenGraphError_msg
#define OpenGraphScrobble_fields &OpenGraphScrobble_msg
#define OpenGraphConfig_fields &OpenGraphConfig_msg
#define AuthConfig_fields &AuthConfig_msg
#define ConfigReply_fields &ConfigReply_msg
#define UserFields_fields &UserFields_msg
#define UserOptions_fields &UserOptions_msg
#define UserRequest_fields &UserRequest_msg
#define User_fields &User_msg
#define FriendsFields_fields &FriendsFields_msg
#define FriendsOptions_fields &FriendsOptions_msg
#define FriendsRequest_fields &FriendsRequest_msg
#define FriendsReply_fields &FriendsReply_msg
#define ShareRequest_fields &ShareRequest_msg
#define ShareReply_fields &ShareReply_msg
#define InboxRequest_fields &InboxRequest_msg
#define InboxReply_fields &InboxReply_msg
#define PermissionsOptions_fields &PermissionsOptions_msg
#define PermissionsRequest_fields &PermissionsRequest_msg
#define PermissionsReply_fields &PermissionsReply_msg
#define GrantPermissionsRequest_fields &GrantPermissionsRequest_msg
#define GrantPermissionsReply_fields &GrantPermissionsReply_msg
#define TransferRequest_fields &TransferRequest_msg

/* Maximum encoded size of messages (where known) */
/* Credential_size depends on runtime parameters */
/* EnableRequest_size depends on runtime parameters */
/* EnableReply_size depends on runtime parameters */
/* DisableRequest_size depends on runtime parameters */
/* RevokeRequest_size depends on runtime parameters */
/* InspectCredentialRequest_size depends on runtime parameters */
/* InspectCredentialReply_size depends on runtime parameters */
/* UserState_size depends on runtime parameters */
/* UpdateUserStateRequest_size depends on runtime parameters */
/* OpenGraphError_size depends on runtime parameters */
#define OpenGraphScrobble_size                   11
/* OpenGraphConfig_size depends on runtime parameters */
/* AuthConfig_size depends on runtime parameters */
/* ConfigReply_size depends on runtime parameters */
#define UserFields_size                          18
#define UserOptions_size                         2
#define UserRequest_size                         24
/* User_size depends on runtime parameters */
#define FriendsFields_size                       6
#define FriendsOptions_size                      28
#define FriendsRequest_size                      38
/* FriendsReply_size depends on runtime parameters */
/* ShareRequest_size depends on runtime parameters */
/* ShareReply_size depends on runtime parameters */
/* InboxRequest_size depends on runtime parameters */
/* InboxReply_size depends on runtime parameters */
#define PermissionsOptions_size                  2
/* PermissionsRequest_size depends on runtime parameters */
/* PermissionsReply_size depends on runtime parameters */
/* GrantPermissionsRequest_size depends on runtime parameters */
/* GrantPermissionsReply_size depends on runtime parameters */
/* TransferRequest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
