/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "keyexchange.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ClientHello, ClientHello, 2)


PB_BIND(BuildInfo, BuildInfo, AUTO)


PB_BIND(LoginCryptoHelloUnion, LoginCryptoHelloUnion, AUTO)


PB_BIND(LoginCryptoDiffieHellmanHello, LoginCryptoDiffieHellmanHello, AUTO)


PB_BIND(FeatureSet, FeatureSet, AUTO)


PB_BIND(APResponseMessage, APResponseMessage, 2)


PB_BIND(APChallenge, APChallenge, AUTO)


PB_BIND(LoginCryptoChallengeUnion, LoginCryptoChallengeUnion, AUTO)


PB_BIND(LoginCryptoDiffieHellmanChallenge, LoginCryptoDiffieHellmanChallenge, AUTO)


PB_BIND(FingerprintChallengeUnion, FingerprintChallengeUnion, AUTO)


PB_BIND(FingerprintGrainChallenge, FingerprintGrainChallenge, AUTO)


PB_BIND(FingerprintHmacRipemdChallenge, FingerprintHmacRipemdChallenge, AUTO)


PB_BIND(PoWChallengeUnion, PoWChallengeUnion, AUTO)


PB_BIND(PoWHashCashChallenge, PoWHashCashChallenge, AUTO)


PB_BIND(CryptoChallengeUnion, CryptoChallengeUnion, AUTO)


PB_BIND(CryptoShannonChallenge, CryptoShannonChallenge, AUTO)


PB_BIND(CryptoRc4Sha1HmacChallenge, CryptoRc4Sha1HmacChallenge, AUTO)


PB_BIND(UpgradeRequiredMessage, UpgradeRequiredMessage, AUTO)


PB_BIND(APLoginFailed, APLoginFailed, AUTO)


PB_BIND(ClientResponsePlaintext, ClientResponsePlaintext, AUTO)


PB_BIND(LoginCryptoResponseUnion, LoginCryptoResponseUnion, AUTO)


PB_BIND(LoginCryptoDiffieHellmanResponse, LoginCryptoDiffieHellmanResponse, AUTO)


PB_BIND(PoWResponseUnion, PoWResponseUnion, AUTO)


PB_BIND(PoWHashCashResponse, PoWHashCashResponse, AUTO)


PB_BIND(CryptoResponseUnion, CryptoResponseUnion, AUTO)


PB_BIND(CryptoShannonResponse, CryptoShannonResponse, AUTO)


PB_BIND(CryptoRc4Sha1HmacResponse, CryptoRc4Sha1HmacResponse, AUTO)










