/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_MERCURY_PB_H_INCLUDED
#define PB_MERCURY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MercuryReply_CachePolicy {
    MercuryReply_CachePolicy_CACHE_NO = 1,
    MercuryReply_CachePolicy_CACHE_PRIVATE = 2,
    MercuryReply_CachePolicy_CACHE_PUBLIC = 3
} MercuryReply_CachePolicy;

/* Struct definitions */
typedef struct _MercuryMultiGetReply {
    pb_callback_t reply;
} MercuryMultiGetReply;

typedef struct _MercuryMultiGetRequest {
    pb_callback_t request;
} MercuryMultiGetRequest;

typedef struct _MercuryRequest {
    pb_callback_t uri;
    pb_callback_t content_type;
    pb_callback_t body;
    pb_callback_t etag;
} MercuryRequest;

typedef struct _UserField {
    pb_callback_t key;
    pb_callback_t value;
} UserField;

typedef struct _Header {
    pb_callback_t uri;
    pb_callback_t content_type;
    pb_callback_t method;
    bool has_status_code;
    int32_t status_code;
    pb_callback_t user_fields;
} Header;

typedef struct _MercuryReply {
    bool has_status_code;
    int32_t status_code;
    pb_callback_t status_message;
    bool has_cache_policy;
    MercuryReply_CachePolicy cache_policy;
    bool has_ttl;
    int32_t ttl;
    pb_callback_t etag;
    pb_callback_t content_type;
    pb_callback_t body;
} MercuryReply;


/* Helper constants for enums */
#define _MercuryReply_CachePolicy_MIN MercuryReply_CachePolicy_CACHE_NO
#define _MercuryReply_CachePolicy_MAX MercuryReply_CachePolicy_CACHE_PUBLIC
#define _MercuryReply_CachePolicy_ARRAYSIZE ((MercuryReply_CachePolicy)(MercuryReply_CachePolicy_CACHE_PUBLIC+1))


/* Initializer values for message structs */
#define MercuryMultiGetRequest_init_default      {{{NULL}, NULL}}
#define MercuryMultiGetReply_init_default        {{{NULL}, NULL}}
#define MercuryRequest_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MercuryReply_init_default                {false, 0, {{NULL}, NULL}, false, _MercuryReply_CachePolicy_MIN, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Header_init_default                      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define UserField_init_default                   {{{NULL}, NULL}, {{NULL}, NULL}}
#define MercuryMultiGetRequest_init_zero         {{{NULL}, NULL}}
#define MercuryMultiGetReply_init_zero           {{{NULL}, NULL}}
#define MercuryRequest_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define MercuryReply_init_zero                   {false, 0, {{NULL}, NULL}, false, _MercuryReply_CachePolicy_MIN, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Header_init_zero                         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define UserField_init_zero                      {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define MercuryMultiGetReply_reply_tag           1
#define MercuryMultiGetRequest_request_tag       1
#define MercuryRequest_uri_tag                   1
#define MercuryRequest_content_type_tag          2
#define MercuryRequest_body_tag                  3
#define MercuryRequest_etag_tag                  4
#define UserField_key_tag                        1
#define UserField_value_tag                      2
#define Header_uri_tag                           1
#define Header_content_type_tag                  2
#define Header_method_tag                        3
#define Header_status_code_tag                   4
#define Header_user_fields_tag                   6
#define MercuryReply_status_code_tag             1
#define MercuryReply_status_message_tag          2
#define MercuryReply_cache_policy_tag            3
#define MercuryReply_ttl_tag                     4
#define MercuryReply_etag_tag                    5
#define MercuryReply_content_type_tag            6
#define MercuryReply_body_tag                    7

/* Struct field encoding specification for nanopb */
#define MercuryMultiGetRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  request,           1)
#define MercuryMultiGetRequest_CALLBACK pb_default_field_callback
#define MercuryMultiGetRequest_DEFAULT NULL
#define MercuryMultiGetRequest_request_MSGTYPE MercuryRequest

#define MercuryMultiGetReply_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  reply,             1)
#define MercuryMultiGetReply_CALLBACK pb_default_field_callback
#define MercuryMultiGetReply_DEFAULT NULL
#define MercuryMultiGetReply_reply_MSGTYPE MercuryReply

#define MercuryRequest_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   content_type,      2) \
X(a, CALLBACK, OPTIONAL, BYTES,    body,              3) \
X(a, CALLBACK, OPTIONAL, BYTES,    etag,              4)
#define MercuryRequest_CALLBACK pb_default_field_callback
#define MercuryRequest_DEFAULT NULL

#define MercuryReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, SINT32,   status_code,       1) \
X(a, CALLBACK, OPTIONAL, STRING,   status_message,    2) \
X(a, STATIC,   OPTIONAL, UENUM,    cache_policy,      3) \
X(a, STATIC,   OPTIONAL, SINT32,   ttl,               4) \
X(a, CALLBACK, OPTIONAL, BYTES,    etag,              5) \
X(a, CALLBACK, OPTIONAL, STRING,   content_type,      6) \
X(a, CALLBACK, OPTIONAL, BYTES,    body,              7)
#define MercuryReply_CALLBACK pb_default_field_callback
#define MercuryReply_DEFAULT (const pb_byte_t*)"\x18\x01\x00"

#define Header_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   content_type,      2) \
X(a, CALLBACK, OPTIONAL, STRING,   method,            3) \
X(a, STATIC,   OPTIONAL, SINT32,   status_code,       4) \
X(a, CALLBACK, REPEATED, MESSAGE,  user_fields,       6)
#define Header_CALLBACK pb_default_field_callback
#define Header_DEFAULT NULL
#define Header_user_fields_MSGTYPE UserField

#define UserField_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   key,               1) \
X(a, CALLBACK, OPTIONAL, BYTES,    value,             2)
#define UserField_CALLBACK pb_default_field_callback
#define UserField_DEFAULT NULL

extern const pb_msgdesc_t MercuryMultiGetRequest_msg;
extern const pb_msgdesc_t MercuryMultiGetReply_msg;
extern const pb_msgdesc_t MercuryRequest_msg;
extern const pb_msgdesc_t MercuryReply_msg;
extern const pb_msgdesc_t Header_msg;
extern const pb_msgdesc_t UserField_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MercuryMultiGetRequest_fields &MercuryMultiGetRequest_msg
#define MercuryMultiGetReply_fields &MercuryMultiGetReply_msg
#define MercuryRequest_fields &MercuryRequest_msg
#define MercuryReply_fields &MercuryReply_msg
#define Header_fields &Header_msg
#define UserField_fields &UserField_msg

/* Maximum encoded size of messages (where known) */
/* MercuryMultiGetRequest_size depends on runtime parameters */
/* MercuryMultiGetReply_size depends on runtime parameters */
/* MercuryRequest_size depends on runtime parameters */
/* MercuryReply_size depends on runtime parameters */
/* Header_size depends on runtime parameters */
/* UserField_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
