/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_MERGEDPROFILE_PB_H_INCLUDED
#define PB_MERGEDPROFILE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MergedProfileReply {
    pb_callback_t username;
    pb_callback_t artistid;
} MergedProfileReply;

typedef struct _MergedProfileRequest {
    char dummy_field;
} MergedProfileRequest;


/* Initializer values for message structs */
#define MergedProfileRequest_init_default        {0}
#define MergedProfileReply_init_default          {{{NULL}, NULL}, {{NULL}, NULL}}
#define MergedProfileRequest_init_zero           {0}
#define MergedProfileReply_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define MergedProfileReply_username_tag          1
#define MergedProfileReply_artistid_tag          2

/* Struct field encoding specification for nanopb */
#define MergedProfileRequest_FIELDLIST(X, a) \

#define MergedProfileRequest_CALLBACK NULL
#define MergedProfileRequest_DEFAULT NULL

#define MergedProfileReply_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   username,          1) \
X(a, CALLBACK, OPTIONAL, STRING,   artistid,          2)
#define MergedProfileReply_CALLBACK pb_default_field_callback
#define MergedProfileReply_DEFAULT NULL

extern const pb_msgdesc_t MergedProfileRequest_msg;
extern const pb_msgdesc_t MergedProfileReply_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MergedProfileRequest_fields &MergedProfileRequest_msg
#define MergedProfileReply_fields &MergedProfileReply_msg

/* Maximum encoded size of messages (where known) */
#define MergedProfileRequest_size                0
/* MergedProfileReply_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
