/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "radio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RadioRequest, RadioRequest, AUTO)


PB_BIND(MultiSeedRequest, MultiSeedRequest, AUTO)


PB_BIND(Feedback, Feedback, AUTO)


PB_BIND(Tracks, Tracks, AUTO)


PB_BIND(Station, Station, AUTO)


PB_BIND(Rules, Rules, AUTO)


PB_BIND(StationResponse, StationResponse, AUTO)


PB_BIND(StationList, StationList, AUTO)


PB_BIND(LikedPlaylist, LikedPlaylist, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

