/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_SPIRC_PB_H_INCLUDED
#define PB_SPIRC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MessageType {
    MessageType_kMessageTypeHello = 1,
    MessageType_kMessageTypeGoodbye = 2,
    MessageType_kMessageTypeProbe = 3,
    MessageType_kMessageTypeNotify = 10,
    MessageType_kMessageTypeLoad = 20,
    MessageType_kMessageTypePlay = 21,
    MessageType_kMessageTypePause = 22,
    MessageType_kMessageTypePlayPause = 23,
    MessageType_kMessageTypeSeek = 24,
    MessageType_kMessageTypePrev = 25,
    MessageType_kMessageTypeNext = 26,
    MessageType_kMessageTypeVolume = 27,
    MessageType_kMessageTypeShuffle = 28,
    MessageType_kMessageTypeRepeat = 29,
    MessageType_kMessageTypeVolumeDown = 31,
    MessageType_kMessageTypeVolumeUp = 32,
    MessageType_kMessageTypeReplace = 33,
    MessageType_kMessageTypeLogout = 34,
    MessageType_kMessageTypeAction = 35
} MessageType;

typedef enum _CapabilityType {
    CapabilityType_kSupportedContexts = 1,
    CapabilityType_kCanBePlayer = 2,
    CapabilityType_kRestrictToLocal = 3,
    CapabilityType_kDeviceType = 4,
    CapabilityType_kGaiaEqConnectId = 5,
    CapabilityType_kSupportsLogout = 6,
    CapabilityType_kIsObservable = 7,
    CapabilityType_kVolumeSteps = 8,
    CapabilityType_kSupportedTypes = 9,
    CapabilityType_kCommandAcks = 10
} CapabilityType;

typedef enum _PlayStatus {
    PlayStatus_kPlayStatusStop = 0,
    PlayStatus_kPlayStatusPlay = 1,
    PlayStatus_kPlayStatusPause = 2,
    PlayStatus_kPlayStatusLoading = 3
} PlayStatus;

/* Struct definitions */
typedef struct _Goodbye {
    pb_callback_t reason;
} Goodbye;

typedef struct _Ad {
    bool has_next;
    int32_t next;
    pb_callback_t ogg_fid;
    pb_callback_t image_fid;
    bool has_duration;
    int32_t duration;
    pb_callback_t click_url;
    pb_callback_t impression_url;
    pb_callback_t product;
    pb_callback_t advertiser;
    pb_callback_t gid;
} Ad;

typedef struct _Capability {
    bool has_typ;
    CapabilityType typ;
    pb_callback_t intValue;
    pb_callback_t stringValue;
} Capability;

typedef struct _DeviceState {
    pb_callback_t sw_version;
    bool has_is_active;
    bool is_active;
    bool has_can_play;
    bool can_play;
    bool has_volume;
    uint32_t volume;
    pb_callback_t name;
    bool has_error_code;
    uint32_t error_code;
    bool has_became_active_at;
    int64_t became_active_at;
    pb_callback_t error_message;
    pb_callback_t capabilities;
    pb_callback_t local_uris;
    pb_callback_t enc_key;
} DeviceState;

typedef struct _TrackRef {
    pb_callback_t gid;
    pb_callback_t uri;
    bool has_queued;
    bool queued;
    pb_callback_t context;
} TrackRef;

typedef struct _State {
    pb_callback_t context_uri;
    bool has_index;
    uint32_t index;
    bool has_position_ms;
    uint32_t position_ms;
    bool has_status;
    PlayStatus status;
    bool has_position_measured_at;
    uint64_t position_measured_at;
    pb_callback_t context_description;
    bool has_shuffle;
    bool shuffle;
    bool has_repeat;
    bool repeat;
    pb_callback_t last_command_ident;
    bool has_last_command_msgid;
    uint32_t last_command_msgid;
    bool has_playing_from_fallback;
    bool playing_from_fallback;
    bool has_row;
    uint32_t row;
    bool has_playing_track_index;
    uint32_t playing_track_index;
    pb_callback_t track;
    bool has_ad;
    Ad ad;
} State;

typedef struct _Frame {
    bool has_version;
    uint32_t version;
    pb_callback_t ident;
    pb_callback_t protocol_version;
    bool has_seq_nr;
    uint32_t seq_nr;
    bool has_typ;
    MessageType typ;
    bool has_device_state;
    DeviceState device_state;
    bool has_goodbye;
    Goodbye goodbye;
    bool has_state;
    State state;
    bool has_position;
    uint32_t position;
    bool has_volume;
    uint32_t volume;
    bool has_state_update_id;
    int64_t state_update_id;
    pb_callback_t recipient;
    pb_callback_t context_player_state;
} Frame;


/* Helper constants for enums */
#define _MessageType_MIN MessageType_kMessageTypeHello
#define _MessageType_MAX MessageType_kMessageTypeAction
#define _MessageType_ARRAYSIZE ((MessageType)(MessageType_kMessageTypeAction+1))

#define _CapabilityType_MIN CapabilityType_kSupportedContexts
#define _CapabilityType_MAX CapabilityType_kCommandAcks
#define _CapabilityType_ARRAYSIZE ((CapabilityType)(CapabilityType_kCommandAcks+1))

#define _PlayStatus_MIN PlayStatus_kPlayStatusStop
#define _PlayStatus_MAX PlayStatus_kPlayStatusLoading
#define _PlayStatus_ARRAYSIZE ((PlayStatus)(PlayStatus_kPlayStatusLoading+1))


/* Initializer values for message structs */
#define Frame_init_default                       {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, _MessageType_MIN, false, DeviceState_init_default, false, Goodbye_init_default, false, State_init_default, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define DeviceState_init_default                 {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Capability_init_default                  {false, _CapabilityType_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define Goodbye_init_default                     {{{NULL}, NULL}}
#define State_init_default                       {{{NULL}, NULL}, false, 0, false, 0, false, _PlayStatus_MIN, false, 0, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, Ad_init_default}
#define TrackRef_init_default                    {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define Ad_init_default                          {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Frame_init_zero                          {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, _MessageType_MIN, false, DeviceState_init_zero, false, Goodbye_init_zero, false, State_init_zero, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define DeviceState_init_zero                    {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Capability_init_zero                     {false, _CapabilityType_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define Goodbye_init_zero                        {{{NULL}, NULL}}
#define State_init_zero                          {{{NULL}, NULL}, false, 0, false, 0, false, _PlayStatus_MIN, false, 0, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, Ad_init_zero}
#define TrackRef_init_zero                       {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define Ad_init_zero                             {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Goodbye_reason_tag                       1
#define Ad_next_tag                              1
#define Ad_ogg_fid_tag                           2
#define Ad_image_fid_tag                         3
#define Ad_duration_tag                          4
#define Ad_click_url_tag                         5
#define Ad_impression_url_tag                    6
#define Ad_product_tag                           7
#define Ad_advertiser_tag                        8
#define Ad_gid_tag                               9
#define Capability_typ_tag                       1
#define Capability_intValue_tag                  2
#define Capability_stringValue_tag               3
#define DeviceState_sw_version_tag               1
#define DeviceState_is_active_tag                10
#define DeviceState_can_play_tag                 11
#define DeviceState_volume_tag                   12
#define DeviceState_name_tag                     13
#define DeviceState_error_code_tag               14
#define DeviceState_became_active_at_tag         15
#define DeviceState_error_message_tag            16
#define DeviceState_capabilities_tag             17
#define DeviceState_local_uris_tag               18
#define DeviceState_enc_key_tag                  19
#define TrackRef_gid_tag                         1
#define TrackRef_uri_tag                         2
#define TrackRef_queued_tag                      3
#define TrackRef_context_tag                     4
#define State_context_uri_tag                    2
#define State_index_tag                          3
#define State_position_ms_tag                    4
#define State_status_tag                         5
#define State_position_measured_at_tag           7
#define State_context_description_tag            8
#define State_shuffle_tag                        13
#define State_repeat_tag                         14
#define State_last_command_ident_tag             20
#define State_last_command_msgid_tag             21
#define State_playing_from_fallback_tag          24
#define State_row_tag                            25
#define State_playing_track_index_tag            26
#define State_track_tag                          27
#define State_ad_tag                             28
#define Frame_version_tag                        1
#define Frame_ident_tag                          2
#define Frame_protocol_version_tag               3
#define Frame_seq_nr_tag                         4
#define Frame_typ_tag                            5
#define Frame_device_state_tag                   7
#define Frame_goodbye_tag                        11
#define Frame_state_tag                          12
#define Frame_position_tag                       13
#define Frame_volume_tag                         14
#define Frame_state_update_id_tag                17
#define Frame_recipient_tag                      18
#define Frame_context_player_state_tag           19

/* Struct field encoding specification for nanopb */
#define Frame_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   version,           1) \
X(a, CALLBACK, OPTIONAL, STRING,   ident,             2) \
X(a, CALLBACK, OPTIONAL, STRING,   protocol_version,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   seq_nr,            4) \
X(a, STATIC,   OPTIONAL, UENUM,    typ,               5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_state,      7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  goodbye,          11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  state,            12) \
X(a, STATIC,   OPTIONAL, UINT32,   position,         13) \
X(a, STATIC,   OPTIONAL, UINT32,   volume,           14) \
X(a, STATIC,   OPTIONAL, INT64,    state_update_id,  17) \
X(a, CALLBACK, REPEATED, STRING,   recipient,        18) \
X(a, CALLBACK, OPTIONAL, BYTES,    context_player_state,  19)
#define Frame_CALLBACK pb_default_field_callback
#define Frame_DEFAULT (const pb_byte_t*)"\x28\x01\x00"
#define Frame_device_state_MSGTYPE DeviceState
#define Frame_goodbye_MSGTYPE Goodbye
#define Frame_state_MSGTYPE State

#define DeviceState_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   sw_version,        1) \
X(a, STATIC,   OPTIONAL, BOOL,     is_active,        10) \
X(a, STATIC,   OPTIONAL, BOOL,     can_play,         11) \
X(a, STATIC,   OPTIONAL, UINT32,   volume,           12) \
X(a, CALLBACK, OPTIONAL, STRING,   name,             13) \
X(a, STATIC,   OPTIONAL, UINT32,   error_code,       14) \
X(a, STATIC,   OPTIONAL, INT64,    became_active_at,  15) \
X(a, CALLBACK, OPTIONAL, STRING,   error_message,    16) \
X(a, CALLBACK, REPEATED, MESSAGE,  capabilities,     17) \
X(a, CALLBACK, REPEATED, STRING,   local_uris,       18) \
X(a, CALLBACK, REPEATED, INT32,    enc_key,          19)
#define DeviceState_CALLBACK pb_default_field_callback
#define DeviceState_DEFAULT NULL
#define DeviceState_capabilities_MSGTYPE Capability

#define Capability_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    typ,               1) \
X(a, CALLBACK, REPEATED, INT64,    intValue,          2) \
X(a, CALLBACK, REPEATED, STRING,   stringValue,       3)
#define Capability_CALLBACK pb_default_field_callback
#define Capability_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define Goodbye_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   reason,            1)
#define Goodbye_CALLBACK pb_default_field_callback
#define Goodbye_DEFAULT NULL

#define State_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   context_uri,       2) \
X(a, STATIC,   OPTIONAL, UINT32,   index,             3) \
X(a, STATIC,   OPTIONAL, UINT32,   position_ms,       4) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            5) \
X(a, STATIC,   OPTIONAL, UINT64,   position_measured_at,   7) \
X(a, CALLBACK, OPTIONAL, STRING,   context_description,   8) \
X(a, STATIC,   OPTIONAL, BOOL,     shuffle,          13) \
X(a, STATIC,   OPTIONAL, BOOL,     repeat,           14) \
X(a, CALLBACK, OPTIONAL, STRING,   last_command_ident,  20) \
X(a, STATIC,   OPTIONAL, UINT32,   last_command_msgid,  21) \
X(a, STATIC,   OPTIONAL, BOOL,     playing_from_fallback,  24) \
X(a, STATIC,   OPTIONAL, UINT32,   row,              25) \
X(a, STATIC,   OPTIONAL, UINT32,   playing_track_index,  26) \
X(a, CALLBACK, REPEATED, MESSAGE,  track,            27) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ad,               28)
#define State_CALLBACK pb_default_field_callback
#define State_DEFAULT NULL
#define State_track_MSGTYPE TrackRef
#define State_ad_MSGTYPE Ad

#define TrackRef_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    gid,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               2) \
X(a, STATIC,   OPTIONAL, BOOL,     queued,            3) \
X(a, CALLBACK, OPTIONAL, STRING,   context,           4)
#define TrackRef_CALLBACK pb_default_field_callback
#define TrackRef_DEFAULT NULL

#define Ad_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    next,              1) \
X(a, CALLBACK, OPTIONAL, BYTES,    ogg_fid,           2) \
X(a, CALLBACK, OPTIONAL, BYTES,    image_fid,         3) \
X(a, STATIC,   OPTIONAL, INT32,    duration,          4) \
X(a, CALLBACK, OPTIONAL, STRING,   click_url,         5) \
X(a, CALLBACK, OPTIONAL, STRING,   impression_url,    6) \
X(a, CALLBACK, OPTIONAL, STRING,   product,           7) \
X(a, CALLBACK, OPTIONAL, STRING,   advertiser,        8) \
X(a, CALLBACK, OPTIONAL, BYTES,    gid,               9)
#define Ad_CALLBACK pb_default_field_callback
#define Ad_DEFAULT NULL

extern const pb_msgdesc_t Frame_msg;
extern const pb_msgdesc_t DeviceState_msg;
extern const pb_msgdesc_t Capability_msg;
extern const pb_msgdesc_t Goodbye_msg;
extern const pb_msgdesc_t State_msg;
extern const pb_msgdesc_t TrackRef_msg;
extern const pb_msgdesc_t Ad_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Frame_fields &Frame_msg
#define DeviceState_fields &DeviceState_msg
#define Capability_fields &Capability_msg
#define Goodbye_fields &Goodbye_msg
#define State_fields &State_msg
#define TrackRef_fields &TrackRef_msg
#define Ad_fields &Ad_msg

/* Maximum encoded size of messages (where known) */
/* Frame_size depends on runtime parameters */
/* DeviceState_size depends on runtime parameters */
/* Capability_size depends on runtime parameters */
/* Goodbye_size depends on runtime parameters */
/* State_size depends on runtime parameters */
/* TrackRef_size depends on runtime parameters */
/* Ad_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
