# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ad-hermes-proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ad-hermes-proxy.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x61\x64-hermes-proxy.proto\"5\n\x04Rule\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05times\x18\x02 \x01(\r\x12\x10\n\x08interval\x18\x03 \x01(\x04\"f\n\tAdRequest\x12\x17\n\x0f\x63lient_language\x18\x01 \x01(\t\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x10\n\x08\x61voidAds\x18\x05 \x03(\t\"6\n\x0f\x41\x64QueueResponse\x12#\n\x0c\x61\x64QueueEntry\x18\x01 \x03(\x0b\x32\r.AdQueueEntry\"$\n\x06\x41\x64\x46ile\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"\xb8\x03\n\x0c\x41\x64QueueEntry\x12\x12\n\nstart_time\x18\x01 \x01(\x04\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x04\x12\x10\n\x08priority\x18\x03 \x01(\x01\x12\r\n\x05token\x18\x04 \x01(\t\x12\x12\n\nad_version\x18\x05 \x01(\r\x12\n\n\x02id\x18\x06 \x01(\t\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x10\n\x08\x63\x61mpaign\x18\x08 \x01(\t\x12\x12\n\nadvertiser\x18\t \x01(\t\x12\x0b\n\x03url\x18\n \x01(\t\x12\x10\n\x08\x64uration\x18\x0b \x01(\x04\x12\x0e\n\x06\x65xpiry\x18\x0c \x01(\x04\x12\x14\n\x0ctracking_url\x18\r \x01(\t\x12\x13\n\x0b\x62\x61nner_type\x18\x0e \x01(\t\x12\x0c\n\x04html\x18\x0f \x01(\t\x12\r\n\x05image\x18\x10 \x01(\t\x12\x18\n\x10\x62\x61\x63kground_image\x18\x11 \x01(\t\x12\x16\n\x0e\x62\x61\x63kground_url\x18\x12 \x01(\t\x12\x18\n\x10\x62\x61\x63kground_color\x18\x13 \x01(\t\x12\r\n\x05title\x18\x14 \x01(\t\x12\x0f\n\x07\x63\x61ption\x18\x15 \x01(\t\x12\x15\n\x04\x66ile\x18\x16 \x03(\x0b\x32\x07.AdFile\x12\x13\n\x04rule\x18\x17 \x03(\x0b\x32\x05.Rule')
)




_RULE = _descriptor.Descriptor(
  name='Rule',
  full_name='Rule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Rule.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='times', full_name='Rule.times', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval', full_name='Rule.interval', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=78,
)


_ADREQUEST = _descriptor.Descriptor(
  name='AdRequest',
  full_name='AdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_language', full_name='AdRequest.client_language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product', full_name='AdRequest.product', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='AdRequest.version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='AdRequest.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avoidAds', full_name='AdRequest.avoidAds', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=182,
)


_ADQUEUERESPONSE = _descriptor.Descriptor(
  name='AdQueueResponse',
  full_name='AdQueueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adQueueEntry', full_name='AdQueueResponse.adQueueEntry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=238,
)


_ADFILE = _descriptor.Descriptor(
  name='AdFile',
  full_name='AdFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AdFile.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='AdFile.format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=276,
)


_ADQUEUEENTRY = _descriptor.Descriptor(
  name='AdQueueEntry',
  full_name='AdQueueEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='AdQueueEntry.start_time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='AdQueueEntry.end_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='AdQueueEntry.priority', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='AdQueueEntry.token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ad_version', full_name='AdQueueEntry.ad_version', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='AdQueueEntry.id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='AdQueueEntry.type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='campaign', full_name='AdQueueEntry.campaign', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='advertiser', full_name='AdQueueEntry.advertiser', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='AdQueueEntry.url', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='AdQueueEntry.duration', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='AdQueueEntry.expiry', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tracking_url', full_name='AdQueueEntry.tracking_url', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='banner_type', full_name='AdQueueEntry.banner_type', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='html', full_name='AdQueueEntry.html', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='AdQueueEntry.image', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='background_image', full_name='AdQueueEntry.background_image', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='background_url', full_name='AdQueueEntry.background_url', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='background_color', full_name='AdQueueEntry.background_color', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='AdQueueEntry.title', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caption', full_name='AdQueueEntry.caption', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file', full_name='AdQueueEntry.file', index=21,
      number=22, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rule', full_name='AdQueueEntry.rule', index=22,
      number=23, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=719,
)

_ADQUEUERESPONSE.fields_by_name['adQueueEntry'].message_type = _ADQUEUEENTRY
_ADQUEUEENTRY.fields_by_name['file'].message_type = _ADFILE
_ADQUEUEENTRY.fields_by_name['rule'].message_type = _RULE
DESCRIPTOR.message_types_by_name['Rule'] = _RULE
DESCRIPTOR.message_types_by_name['AdRequest'] = _ADREQUEST
DESCRIPTOR.message_types_by_name['AdQueueResponse'] = _ADQUEUERESPONSE
DESCRIPTOR.message_types_by_name['AdFile'] = _ADFILE
DESCRIPTOR.message_types_by_name['AdQueueEntry'] = _ADQUEUEENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Rule = _reflection.GeneratedProtocolMessageType('Rule', (_message.Message,), dict(
  DESCRIPTOR = _RULE,
  __module__ = 'ad_hermes_proxy_pb2'
  # @@protoc_insertion_point(class_scope:Rule)
  ))
_sym_db.RegisterMessage(Rule)

AdRequest = _reflection.GeneratedProtocolMessageType('AdRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADREQUEST,
  __module__ = 'ad_hermes_proxy_pb2'
  # @@protoc_insertion_point(class_scope:AdRequest)
  ))
_sym_db.RegisterMessage(AdRequest)

AdQueueResponse = _reflection.GeneratedProtocolMessageType('AdQueueResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADQUEUERESPONSE,
  __module__ = 'ad_hermes_proxy_pb2'
  # @@protoc_insertion_point(class_scope:AdQueueResponse)
  ))
_sym_db.RegisterMessage(AdQueueResponse)

AdFile = _reflection.GeneratedProtocolMessageType('AdFile', (_message.Message,), dict(
  DESCRIPTOR = _ADFILE,
  __module__ = 'ad_hermes_proxy_pb2'
  # @@protoc_insertion_point(class_scope:AdFile)
  ))
_sym_db.RegisterMessage(AdFile)

AdQueueEntry = _reflection.GeneratedProtocolMessageType('AdQueueEntry', (_message.Message,), dict(
  DESCRIPTOR = _ADQUEUEENTRY,
  __module__ = 'ad_hermes_proxy_pb2'
  # @@protoc_insertion_point(class_scope:AdQueueEntry)
  ))
_sym_db.RegisterMessage(AdQueueEntry)


# @@protoc_insertion_point(module_scope)
