# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facebook-publish.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='facebook-publish.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x66\x61\x63\x65\x62ook-publish.proto\"7\n\nEventReply\x12\x0e\n\x06queued\x18\x01 \x01(\x05\x12\x19\n\x05retry\x18\x02 \x01(\x0b\x32\n.RetryInfo\"3\n\tRetryInfo\x12\x13\n\x0bretry_delay\x18\x01 \x01(\x05\x12\x11\n\tmax_retry\x18\x02 \x01(\x05\"%\n\x02Id\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x03\">\n\x05Start\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\x13\n\x0b\x63ontext_uri\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\"\x18\n\x04Seek\x12\x10\n\x08\x65nd_time\x18\x01 \x01(\x03\"1\n\x05Pause\x12\x16\n\x0eseconds_played\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03\"2\n\x06Resume\x12\x16\n\x0eseconds_played\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03\"/\n\x03\x45nd\x12\x16\n\x0eseconds_played\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03\"\x87\x01\n\x05\x45vent\x12\x0f\n\x02id\x18\x01 \x01(\x0b\x32\x03.Id\x12\x15\n\x05start\x18\x02 \x01(\x0b\x32\x06.Start\x12\x13\n\x04seek\x18\x03 \x01(\x0b\x32\x05.Seek\x12\x15\n\x05pause\x18\x04 \x01(\x0b\x32\x06.Pause\x12\x17\n\x06resume\x18\x05 \x01(\x0b\x32\x07.Resume\x12\x11\n\x03\x65nd\x18\x06 \x01(\x0b\x32\x04.End')
)




_EVENTREPLY = _descriptor.Descriptor(
  name='EventReply',
  full_name='EventReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queued', full_name='EventReply.queued', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retry', full_name='EventReply.retry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=81,
)


_RETRYINFO = _descriptor.Descriptor(
  name='RetryInfo',
  full_name='RetryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retry_delay', full_name='RetryInfo.retry_delay', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_retry', full_name='RetryInfo.max_retry', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=134,
)


_ID = _descriptor.Descriptor(
  name='Id',
  full_name='Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='Id.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='Id.start_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=173,
)


_START = _descriptor.Descriptor(
  name='Start',
  full_name='Start',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='Start.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context_uri', full_name='Start.context_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='Start.end_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=237,
)


_SEEK = _descriptor.Descriptor(
  name='Seek',
  full_name='Seek',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='end_time', full_name='Seek.end_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=263,
)


_PAUSE = _descriptor.Descriptor(
  name='Pause',
  full_name='Pause',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds_played', full_name='Pause.seconds_played', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='Pause.end_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=314,
)


_RESUME = _descriptor.Descriptor(
  name='Resume',
  full_name='Resume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds_played', full_name='Resume.seconds_played', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='Resume.end_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=366,
)


_END = _descriptor.Descriptor(
  name='End',
  full_name='End',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds_played', full_name='End.seconds_played', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='End.end_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=415,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Event.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='Event.start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seek', full_name='Event.seek', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pause', full_name='Event.pause', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resume', full_name='Event.resume', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='Event.end', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=553,
)

_EVENTREPLY.fields_by_name['retry'].message_type = _RETRYINFO
_EVENT.fields_by_name['id'].message_type = _ID
_EVENT.fields_by_name['start'].message_type = _START
_EVENT.fields_by_name['seek'].message_type = _SEEK
_EVENT.fields_by_name['pause'].message_type = _PAUSE
_EVENT.fields_by_name['resume'].message_type = _RESUME
_EVENT.fields_by_name['end'].message_type = _END
DESCRIPTOR.message_types_by_name['EventReply'] = _EVENTREPLY
DESCRIPTOR.message_types_by_name['RetryInfo'] = _RETRYINFO
DESCRIPTOR.message_types_by_name['Id'] = _ID
DESCRIPTOR.message_types_by_name['Start'] = _START
DESCRIPTOR.message_types_by_name['Seek'] = _SEEK
DESCRIPTOR.message_types_by_name['Pause'] = _PAUSE
DESCRIPTOR.message_types_by_name['Resume'] = _RESUME
DESCRIPTOR.message_types_by_name['End'] = _END
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventReply = _reflection.GeneratedProtocolMessageType('EventReply', (_message.Message,), dict(
  DESCRIPTOR = _EVENTREPLY,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:EventReply)
  ))
_sym_db.RegisterMessage(EventReply)

RetryInfo = _reflection.GeneratedProtocolMessageType('RetryInfo', (_message.Message,), dict(
  DESCRIPTOR = _RETRYINFO,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:RetryInfo)
  ))
_sym_db.RegisterMessage(RetryInfo)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:Id)
  ))
_sym_db.RegisterMessage(Id)

Start = _reflection.GeneratedProtocolMessageType('Start', (_message.Message,), dict(
  DESCRIPTOR = _START,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:Start)
  ))
_sym_db.RegisterMessage(Start)

Seek = _reflection.GeneratedProtocolMessageType('Seek', (_message.Message,), dict(
  DESCRIPTOR = _SEEK,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:Seek)
  ))
_sym_db.RegisterMessage(Seek)

Pause = _reflection.GeneratedProtocolMessageType('Pause', (_message.Message,), dict(
  DESCRIPTOR = _PAUSE,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:Pause)
  ))
_sym_db.RegisterMessage(Pause)

Resume = _reflection.GeneratedProtocolMessageType('Resume', (_message.Message,), dict(
  DESCRIPTOR = _RESUME,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:Resume)
  ))
_sym_db.RegisterMessage(Resume)

End = _reflection.GeneratedProtocolMessageType('End', (_message.Message,), dict(
  DESCRIPTOR = _END,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:End)
  ))
_sym_db.RegisterMessage(End)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'facebook_publish_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  ))
_sym_db.RegisterMessage(Event)


# @@protoc_insertion_point(module_scope)
