# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mergedprofile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mergedprofile.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13mergedprofile.proto\"\x16\n\x14MergedProfileRequest\"8\n\x12MergedProfileReply\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x61rtistid\x18\x02 \x01(\t')
)




_MERGEDPROFILEREQUEST = _descriptor.Descriptor(
  name='MergedProfileRequest',
  full_name='MergedProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=45,
)


_MERGEDPROFILEREPLY = _descriptor.Descriptor(
  name='MergedProfileReply',
  full_name='MergedProfileReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='MergedProfileReply.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='artistid', full_name='MergedProfileReply.artistid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['MergedProfileRequest'] = _MERGEDPROFILEREQUEST
DESCRIPTOR.message_types_by_name['MergedProfileReply'] = _MERGEDPROFILEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MergedProfileRequest = _reflection.GeneratedProtocolMessageType('MergedProfileRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERGEDPROFILEREQUEST,
  __module__ = 'mergedprofile_pb2'
  # @@protoc_insertion_point(class_scope:MergedProfileRequest)
  ))
_sym_db.RegisterMessage(MergedProfileRequest)

MergedProfileReply = _reflection.GeneratedProtocolMessageType('MergedProfileReply', (_message.Message,), dict(
  DESCRIPTOR = _MERGEDPROFILEREPLY,
  __module__ = 'mergedprofile_pb2'
  # @@protoc_insertion_point(class_scope:MergedProfileReply)
  ))
_sym_db.RegisterMessage(MergedProfileReply)


# @@protoc_insertion_point(module_scope)
