/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "authentication.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ClientResponseEncrypted, ClientResponseEncrypted, 2)


PB_BIND(LoginCredentials, LoginCredentials, AUTO)


PB_BIND(FingerprintResponseUnion, FingerprintResponseUnion, AUTO)


PB_BIND(FingerprintGrainResponse, FingerprintGrainResponse, AUTO)


PB_BIND(FingerprintHmacRipemdResponse, FingerprintHmacRipemdResponse, AUTO)


PB_BIND(PeerTicketUnion, PeerTicketUnion, AUTO)


PB_BIND(PeerTicketPublicKey, PeerTicketPublicKey, AUTO)


PB_BIND(PeerTicketOld, PeerTicketOld, AUTO)


PB_BIND(SystemInfo, SystemInfo, 2)


PB_BIND(LibspotifyAppKey, LibspotifyAppKey, AUTO)


PB_BIND(ClientInfo, ClientInfo, AUTO)


PB_BIND(ClientInfoFacebook, ClientInfoFacebook, AUTO)


PB_BIND(APWelcome, APWelcome, 2)


PB_BIND(AccountInfo, AccountInfo, AUTO)


PB_BIND(AccountInfoSpotify, AccountInfoSpotify, AUTO)


PB_BIND(AccountInfoFacebook, AccountInfoFacebook, AUTO)









