/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "facebook.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Credential, Credential, AUTO)


PB_BIND(EnableRequest, EnableRequest, AUTO)


PB_BIND(EnableReply, EnableReply, AUTO)


PB_BIND(DisableRequest, DisableRequest, AUTO)


PB_BIND(RevokeRequest, RevokeRequest, AUTO)


PB_BIND(InspectCredentialRequest, InspectCredentialRequest, AUTO)


PB_BIND(InspectCredentialReply, InspectCredentialReply, AUTO)


PB_BIND(UserState, UserState, AUTO)


PB_BIND(UpdateUserStateRequest, UpdateUserStateRequest, AUTO)


PB_BIND(OpenGraphError, OpenGraphError, AUTO)


PB_BIND(OpenGraphScrobble, OpenGraphScrobble, AUTO)


PB_BIND(OpenGraphConfig, OpenGraphConfig, AUTO)


PB_BIND(AuthConfig, AuthConfig, AUTO)


PB_BIND(ConfigReply, ConfigReply, AUTO)


PB_BIND(UserFields, UserFields, AUTO)


PB_BIND(UserOptions, UserOptions, AUTO)


PB_BIND(UserRequest, UserRequest, AUTO)


PB_BIND(User, User, AUTO)


PB_BIND(FriendsFields, FriendsFields, AUTO)


PB_BIND(FriendsOptions, FriendsOptions, AUTO)


PB_BIND(FriendsRequest, FriendsRequest, AUTO)


PB_BIND(FriendsReply, FriendsReply, AUTO)


PB_BIND(ShareRequest, ShareRequest, AUTO)


PB_BIND(ShareReply, ShareReply, AUTO)


PB_BIND(InboxRequest, InboxRequest, AUTO)


PB_BIND(InboxReply, InboxReply, AUTO)


PB_BIND(PermissionsOptions, PermissionsOptions, AUTO)


PB_BIND(PermissionsRequest, PermissionsRequest, AUTO)


PB_BIND(PermissionsReply, PermissionsReply, AUTO)


PB_BIND(GrantPermissionsRequest, GrantPermissionsRequest, AUTO)


PB_BIND(GrantPermissionsReply, GrantPermissionsReply, AUTO)


PB_BIND(TransferRequest, TransferRequest, AUTO)



