/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "mergedprofile.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MergedProfileRequest, MergedProfileRequest, AUTO)


PB_BIND(MergedProfileReply, MergedProfileReply, AUTO)



