/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_PLAYLIST_PB_H_INCLUDED
#define PB_PLAYLIST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _DownloadFormat_Codec {
    DownloadFormat_Codec_CODEC_UNKNOWN = 0,
    DownloadFormat_Codec_OGG_VORBIS = 1,
    DownloadFormat_Codec_FLAC = 2,
    DownloadFormat_Codec_MPEG_1_LAYER_3 = 3
} DownloadFormat_Codec;

typedef enum _ClientIssue_Level {
    ClientIssue_Level_LEVEL_UNKNOWN = 0,
    ClientIssue_Level_LEVEL_DEBUG = 1,
    ClientIssue_Level_LEVEL_INFO = 2,
    ClientIssue_Level_LEVEL_NOTICE = 3,
    ClientIssue_Level_LEVEL_WARNING = 4,
    ClientIssue_Level_LEVEL_ERROR = 5
} ClientIssue_Level;

typedef enum _ClientIssue_Code {
    ClientIssue_Code_CODE_UNKNOWN = 0,
    ClientIssue_Code_CODE_INDEX_OUT_OF_BOUNDS = 1,
    ClientIssue_Code_CODE_VERSION_MISMATCH = 2,
    ClientIssue_Code_CODE_CACHED_CHANGE = 3,
    ClientIssue_Code_CODE_OFFLINE_CHANGE = 4,
    ClientIssue_Code_CODE_CONCURRENT_CHANGE = 5
} ClientIssue_Code;

typedef enum _ClientResolveAction_Code {
    ClientResolveAction_Code_CODE_UNKNOWN = 0,
    ClientResolveAction_Code_CODE_NO_ACTION = 1,
    ClientResolveAction_Code_CODE_RETRY = 2,
    ClientResolveAction_Code_CODE_RELOAD = 3,
    ClientResolveAction_Code_CODE_DISCARD_LOCAL_CHANGES = 4,
    ClientResolveAction_Code_CODE_SEND_DUMP = 5,
    ClientResolveAction_Code_CODE_DISPLAY_ERROR_MESSAGE = 6
} ClientResolveAction_Code;

typedef enum _ClientResolveAction_Initiator {
    ClientResolveAction_Initiator_INITIATOR_UNKNOWN = 0,
    ClientResolveAction_Initiator_INITIATOR_SERVER = 1,
    ClientResolveAction_Initiator_INITIATOR_CLIENT = 2
} ClientResolveAction_Initiator;

typedef enum _ItemAttributesPartialState_ItemAttributeKind {
    ItemAttributesPartialState_ItemAttributeKind_ITEM_UNKNOWN = 0,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_ADDED_BY = 1,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_TIMESTAMP = 2,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_MESSAGE = 3,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_SEEN = 4,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_DOWNLOAD_COUNT = 5,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_DOWNLOAD_FORMAT = 6,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_SEVENDIGITAL_ID = 7,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_SEVENDIGITAL_LEFT = 8,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_SEEN_AT = 9,
    ItemAttributesPartialState_ItemAttributeKind_ITEM_PUBLIC = 10
} ItemAttributesPartialState_ItemAttributeKind;

typedef enum _ListAttributesPartialState_ListAttributeKind {
    ListAttributesPartialState_ListAttributeKind_LIST_UNKNOWN = 0,
    ListAttributesPartialState_ListAttributeKind_LIST_NAME = 1,
    ListAttributesPartialState_ListAttributeKind_LIST_DESCRIPTION = 2,
    ListAttributesPartialState_ListAttributeKind_LIST_PICTURE = 3,
    ListAttributesPartialState_ListAttributeKind_LIST_COLLABORATIVE = 4,
    ListAttributesPartialState_ListAttributeKind_LIST_PL3_VERSION = 5,
    ListAttributesPartialState_ListAttributeKind_LIST_DELETED_BY_OWNER = 6,
    ListAttributesPartialState_ListAttributeKind_LIST_RESTRICTED_COLLABORATIVE = 7
} ListAttributesPartialState_ListAttributeKind;

typedef enum _Op_Kind {
    Op_Kind_KIND_UNKNOWN = 0,
    Op_Kind_ADD = 2,
    Op_Kind_REM = 3,
    Op_Kind_MOV = 4,
    Op_Kind_UPDATE_ITEM_ATTRIBUTES = 5,
    Op_Kind_UPDATE_LIST_ATTRIBUTES = 6
} Op_Kind;

typedef enum _ChangeSet_Kind {
    ChangeSet_Kind_KIND_UNKNOWN = 0,
    ChangeSet_Kind_DELTA = 2,
    ChangeSet_Kind_MERGE = 3
} ChangeSet_Kind;

/* Struct definitions */
typedef struct _Diff {
    pb_callback_t from_revision;
    pb_callback_t ops;
    pb_callback_t to_revision;
} Diff;

typedef struct _OpList {
    pb_callback_t ops;
} OpList;

typedef struct _StringAttribute {
    pb_callback_t key;
    pb_callback_t value;
} StringAttribute;

typedef struct _StringAttributes {
    pb_callback_t attribute;
} StringAttributes;

typedef struct _ChangeInfo {
    pb_callback_t user;
    bool has_timestamp;
    int32_t timestamp;
    bool has_admin;
    bool admin;
    bool has_undo;
    bool undo;
    bool has_redo;
    bool redo;
    bool has_merge;
    bool merge;
    bool has_compressed;
    bool compressed;
    bool has_migration;
    bool migration;
} ChangeInfo;

typedef struct _ClientIssue {
    bool has_level;
    ClientIssue_Level level;
    bool has_code;
    ClientIssue_Code code;
    bool has_repeatCount;
    int32_t repeatCount;
} ClientIssue;

typedef struct _ClientResolveAction {
    bool has_code;
    ClientResolveAction_Code code;
    bool has_initiator;
    ClientResolveAction_Initiator initiator;
} ClientResolveAction;

typedef struct _ContentRange {
    bool has_pos;
    int32_t pos;
    bool has_length;
    int32_t length;
} ContentRange;

typedef struct _DownloadFormat {
    bool has_codec;
    DownloadFormat_Codec codec;
} DownloadFormat;

typedef struct _ListAttributes {
    pb_callback_t name;
    pb_callback_t description;
    pb_callback_t picture;
    bool has_collaborative;
    bool collaborative;
    pb_callback_t pl3_version;
    bool has_deleted_by_owner;
    bool deleted_by_owner;
    bool has_restricted_collaborative;
    bool restricted_collaborative;
    bool has_deprecated_client_id;
    int64_t deprecated_client_id;
    bool has_public_starred;
    bool public_starred;
    pb_callback_t client_id;
} ListAttributes;

typedef struct _ListChecksum {
    bool has_version;
    int32_t version;
    pb_callback_t sha1;
} ListChecksum;

typedef struct _ListItems {
    bool has_pos;
    int32_t pos;
    bool has_truncated;
    bool truncated;
    pb_callback_t items;
} ListItems;

typedef struct _Add {
    bool has_fromIndex;
    int32_t fromIndex;
    pb_callback_t items;
    bool has_list_checksum;
    ListChecksum list_checksum;
    bool has_addLast;
    bool addLast;
    bool has_addFirst;
    bool addFirst;
} Add;

typedef struct _Delta {
    pb_callback_t base_version;
    pb_callback_t ops;
    bool has_info;
    ChangeInfo info;
} Delta;

typedef struct _ItemAttributes {
    pb_callback_t added_by;
    bool has_timestamp;
    int64_t timestamp;
    pb_callback_t message;
    bool has_seen;
    bool seen;
    bool has_download_count;
    int64_t download_count;
    bool has_download_format;
    DownloadFormat download_format;
    pb_callback_t sevendigital_id;
    bool has_sevendigital_left;
    int64_t sevendigital_left;
    bool has_seen_at;
    int64_t seen_at;
    bool has_public;
    bool public;
} ItemAttributes;

typedef struct _ListAttributesPartialState {
    bool has_values;
    ListAttributes values;
    pb_callback_t no_value;
} ListAttributesPartialState;

typedef struct _ListContentSelection {
    bool has_wantRevision;
    bool wantRevision;
    bool has_wantLength;
    bool wantLength;
    bool has_wantAttributes;
    bool wantAttributes;
    bool has_wantChecksum;
    bool wantChecksum;
    bool has_wantContent;
    bool wantContent;
    bool has_contentRange;
    ContentRange contentRange;
    bool has_wantDiff;
    bool wantDiff;
    pb_callback_t baseRevision;
    pb_callback_t hintRevision;
    bool has_wantNothingIfUpToDate;
    bool wantNothingIfUpToDate;
    bool has_wantResolveAction;
    bool wantResolveAction;
    pb_callback_t issues;
    pb_callback_t resolveAction;
} ListContentSelection;

typedef struct _ListDump {
    pb_callback_t latestRevision;
    bool has_length;
    int32_t length;
    bool has_attributes;
    ListAttributes attributes;
    bool has_checksum;
    ListChecksum checksum;
    bool has_contents;
    ListItems contents;
    pb_callback_t pendingDeltas;
} ListDump;

typedef struct _Merge {
    pb_callback_t base_version;
    pb_callback_t merge_version;
    bool has_info;
    ChangeInfo info;
} Merge;

typedef struct _Mov {
    bool has_fromIndex;
    int32_t fromIndex;
    bool has_length;
    int32_t length;
    bool has_toIndex;
    int32_t toIndex;
    bool has_list_checksum;
    ListChecksum list_checksum;
    bool has_items_checksum;
    ListChecksum items_checksum;
    bool has_uris_checksum;
    ListChecksum uris_checksum;
} Mov;

typedef struct _Rem {
    bool has_fromIndex;
    int32_t fromIndex;
    bool has_length;
    int32_t length;
    pb_callback_t items;
    bool has_list_checksum;
    ListChecksum list_checksum;
    bool has_items_checksum;
    ListChecksum items_checksum;
    bool has_uris_checksum;
    ListChecksum uris_checksum;
    bool has_itemsAsKey;
    bool itemsAsKey;
} Rem;

typedef struct _SelectedListContent {
    pb_callback_t revision;
    bool has_length;
    int32_t length;
    bool has_attributes;
    ListAttributes attributes;
    bool has_checksum;
    ListChecksum checksum;
    bool has_contents;
    ListItems contents;
    bool has_diff;
    Diff diff;
    bool has_syncResult;
    Diff syncResult;
    pb_callback_t resultingRevisions;
    bool has_multipleHeads;
    bool multipleHeads;
    bool has_upToDate;
    bool upToDate;
    pb_callback_t resolveAction;
    pb_callback_t issues;
    pb_callback_t nonces;
} SelectedListContent;

typedef struct _ChangeSet {
    bool has_kind;
    ChangeSet_Kind kind;
    bool has_delta;
    Delta delta;
    bool has_merge;
    Merge merge;
} ChangeSet;

typedef struct _Item {
    pb_callback_t uri;
    bool has_attributes;
    ItemAttributes attributes;
} Item;

typedef struct _ItemAttributesPartialState {
    bool has_values;
    ItemAttributes values;
    pb_callback_t no_value;
} ItemAttributesPartialState;

typedef struct _ListChanges {
    pb_callback_t baseRevision;
    pb_callback_t deltas;
    bool has_wantResultingRevisions;
    bool wantResultingRevisions;
    bool has_wantSyncResult;
    bool wantSyncResult;
    bool has_dump;
    ListDump dump;
    pb_callback_t nonces;
} ListChanges;

typedef struct _UpdateListAttributes {
    bool has_new_attributes;
    ListAttributesPartialState new_attributes;
    bool has_old_attributes;
    ListAttributesPartialState old_attributes;
    bool has_list_checksum;
    ListChecksum list_checksum;
    bool has_old_attributes_checksum;
    ListChecksum old_attributes_checksum;
} UpdateListAttributes;

typedef struct _RevisionTaggedChangeSet {
    pb_callback_t revision;
    bool has_change_set;
    ChangeSet change_set;
} RevisionTaggedChangeSet;

typedef struct _UpdateItemAttributes {
    bool has_index;
    int32_t index;
    bool has_new_attributes;
    ItemAttributesPartialState new_attributes;
    bool has_old_attributes;
    ItemAttributesPartialState old_attributes;
    bool has_list_checksum;
    ListChecksum list_checksum;
    bool has_old_attributes_checksum;
    ListChecksum old_attributes_checksum;
} UpdateItemAttributes;

typedef struct _Op {
    bool has_kind;
    Op_Kind kind;
    bool has_add;
    Add add;
    bool has_rem;
    Rem rem;
    bool has_mov;
    Mov mov;
    bool has_update_item_attributes;
    UpdateItemAttributes update_item_attributes;
    bool has_update_list_attributes;
    UpdateListAttributes update_list_attributes;
} Op;


/* Helper constants for enums */
#define _DownloadFormat_Codec_MIN DownloadFormat_Codec_CODEC_UNKNOWN
#define _DownloadFormat_Codec_MAX DownloadFormat_Codec_MPEG_1_LAYER_3
#define _DownloadFormat_Codec_ARRAYSIZE ((DownloadFormat_Codec)(DownloadFormat_Codec_MPEG_1_LAYER_3+1))

#define _ClientIssue_Level_MIN ClientIssue_Level_LEVEL_UNKNOWN
#define _ClientIssue_Level_MAX ClientIssue_Level_LEVEL_ERROR
#define _ClientIssue_Level_ARRAYSIZE ((ClientIssue_Level)(ClientIssue_Level_LEVEL_ERROR+1))

#define _ClientIssue_Code_MIN ClientIssue_Code_CODE_UNKNOWN
#define _ClientIssue_Code_MAX ClientIssue_Code_CODE_CONCURRENT_CHANGE
#define _ClientIssue_Code_ARRAYSIZE ((ClientIssue_Code)(ClientIssue_Code_CODE_CONCURRENT_CHANGE+1))

#define _ClientResolveAction_Code_MIN ClientResolveAction_Code_CODE_UNKNOWN
#define _ClientResolveAction_Code_MAX ClientResolveAction_Code_CODE_DISPLAY_ERROR_MESSAGE
#define _ClientResolveAction_Code_ARRAYSIZE ((ClientResolveAction_Code)(ClientResolveAction_Code_CODE_DISPLAY_ERROR_MESSAGE+1))

#define _ClientResolveAction_Initiator_MIN ClientResolveAction_Initiator_INITIATOR_UNKNOWN
#define _ClientResolveAction_Initiator_MAX ClientResolveAction_Initiator_INITIATOR_CLIENT
#define _ClientResolveAction_Initiator_ARRAYSIZE ((ClientResolveAction_Initiator)(ClientResolveAction_Initiator_INITIATOR_CLIENT+1))

#define _ItemAttributesPartialState_ItemAttributeKind_MIN ItemAttributesPartialState_ItemAttributeKind_ITEM_UNKNOWN
#define _ItemAttributesPartialState_ItemAttributeKind_MAX ItemAttributesPartialState_ItemAttributeKind_ITEM_PUBLIC
#define _ItemAttributesPartialState_ItemAttributeKind_ARRAYSIZE ((ItemAttributesPartialState_ItemAttributeKind)(ItemAttributesPartialState_ItemAttributeKind_ITEM_PUBLIC+1))

#define _ListAttributesPartialState_ListAttributeKind_MIN ListAttributesPartialState_ListAttributeKind_LIST_UNKNOWN
#define _ListAttributesPartialState_ListAttributeKind_MAX ListAttributesPartialState_ListAttributeKind_LIST_RESTRICTED_COLLABORATIVE
#define _ListAttributesPartialState_ListAttributeKind_ARRAYSIZE ((ListAttributesPartialState_ListAttributeKind)(ListAttributesPartialState_ListAttributeKind_LIST_RESTRICTED_COLLABORATIVE+1))

#define _Op_Kind_MIN Op_Kind_KIND_UNKNOWN
#define _Op_Kind_MAX Op_Kind_UPDATE_LIST_ATTRIBUTES
#define _Op_Kind_ARRAYSIZE ((Op_Kind)(Op_Kind_UPDATE_LIST_ATTRIBUTES+1))

#define _ChangeSet_Kind_MIN ChangeSet_Kind_KIND_UNKNOWN
#define _ChangeSet_Kind_MAX ChangeSet_Kind_MERGE
#define _ChangeSet_Kind_ARRAYSIZE ((ChangeSet_Kind)(ChangeSet_Kind_MERGE+1))


/* Initializer values for message structs */
#define ListChecksum_init_default                {false, 0, {{NULL}, NULL}}
#define DownloadFormat_init_default              {false, _DownloadFormat_Codec_MIN}
#define ListAttributes_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define ItemAttributes_init_default              {{{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, DownloadFormat_init_default, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define StringAttribute_init_default             {{{NULL}, NULL}, {{NULL}, NULL}}
#define StringAttributes_init_default            {{{NULL}, NULL}}
#define ClientIssue_init_default                 {false, _ClientIssue_Level_MIN, false, _ClientIssue_Code_MIN, false, 0}
#define ClientResolveAction_init_default         {false, _ClientResolveAction_Code_MIN, false, _ClientResolveAction_Initiator_MIN}
#define Item_init_default                        {{{NULL}, NULL}, false, ItemAttributes_init_default}
#define ListItems_init_default                   {false, 0, false, 0, {{NULL}, NULL}}
#define ContentRange_init_default                {false, 0, false, 0}
#define ListContentSelection_init_default        {false, 0, false, 0, false, 0, false, 0, false, 0, false, ContentRange_init_default, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Add_init_default                         {false, 0, {{NULL}, NULL}, false, ListChecksum_init_default, false, 0, false, 0}
#define Rem_init_default                         {false, 0, false, 0, {{NULL}, NULL}, false, ListChecksum_init_default, false, ListChecksum_init_default, false, ListChecksum_init_default, false, 0}
#define Mov_init_default                         {false, 0, false, 0, false, 0, false, ListChecksum_init_default, false, ListChecksum_init_default, false, ListChecksum_init_default}
#define ItemAttributesPartialState_init_default  {false, ItemAttributes_init_default, {{NULL}, NULL}}
#define ListAttributesPartialState_init_default  {false, ListAttributes_init_default, {{NULL}, NULL}}
#define UpdateItemAttributes_init_default        {false, 0, false, ItemAttributesPartialState_init_default, false, ItemAttributesPartialState_init_default, false, ListChecksum_init_default, false, ListChecksum_init_default}
#define UpdateListAttributes_init_default        {false, ListAttributesPartialState_init_default, false, ListAttributesPartialState_init_default, false, ListChecksum_init_default, false, ListChecksum_init_default}
#define Op_init_default                          {false, _Op_Kind_MIN, false, Add_init_default, false, Rem_init_default, false, Mov_init_default, false, UpdateItemAttributes_init_default, false, UpdateListAttributes_init_default}
#define OpList_init_default                      {{{NULL}, NULL}}
#define ChangeInfo_init_default                  {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Delta_init_default                       {{{NULL}, NULL}, {{NULL}, NULL}, false, ChangeInfo_init_default}
#define Merge_init_default                       {{{NULL}, NULL}, {{NULL}, NULL}, false, ChangeInfo_init_default}
#define ChangeSet_init_default                   {false, _ChangeSet_Kind_MIN, false, Delta_init_default, false, Merge_init_default}
#define RevisionTaggedChangeSet_init_default     {{{NULL}, NULL}, false, ChangeSet_init_default}
#define Diff_init_default                        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ListDump_init_default                    {{{NULL}, NULL}, false, 0, false, ListAttributes_init_default, false, ListChecksum_init_default, false, ListItems_init_default, {{NULL}, NULL}}
#define ListChanges_init_default                 {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, ListDump_init_default, {{NULL}, NULL}}
#define SelectedListContent_init_default         {{{NULL}, NULL}, false, 0, false, ListAttributes_init_default, false, ListChecksum_init_default, false, ListItems_init_default, false, Diff_init_default, false, Diff_init_default, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ListChecksum_init_zero                   {false, 0, {{NULL}, NULL}}
#define DownloadFormat_init_zero                 {false, _DownloadFormat_Codec_MIN}
#define ListAttributes_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define ItemAttributes_init_zero                 {{{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, DownloadFormat_init_zero, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define StringAttribute_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}}
#define StringAttributes_init_zero               {{{NULL}, NULL}}
#define ClientIssue_init_zero                    {false, _ClientIssue_Level_MIN, false, _ClientIssue_Code_MIN, false, 0}
#define ClientResolveAction_init_zero            {false, _ClientResolveAction_Code_MIN, false, _ClientResolveAction_Initiator_MIN}
#define Item_init_zero                           {{{NULL}, NULL}, false, ItemAttributes_init_zero}
#define ListItems_init_zero                      {false, 0, false, 0, {{NULL}, NULL}}
#define ContentRange_init_zero                   {false, 0, false, 0}
#define ListContentSelection_init_zero           {false, 0, false, 0, false, 0, false, 0, false, 0, false, ContentRange_init_zero, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Add_init_zero                            {false, 0, {{NULL}, NULL}, false, ListChecksum_init_zero, false, 0, false, 0}
#define Rem_init_zero                            {false, 0, false, 0, {{NULL}, NULL}, false, ListChecksum_init_zero, false, ListChecksum_init_zero, false, ListChecksum_init_zero, false, 0}
#define Mov_init_zero                            {false, 0, false, 0, false, 0, false, ListChecksum_init_zero, false, ListChecksum_init_zero, false, ListChecksum_init_zero}
#define ItemAttributesPartialState_init_zero     {false, ItemAttributes_init_zero, {{NULL}, NULL}}
#define ListAttributesPartialState_init_zero     {false, ListAttributes_init_zero, {{NULL}, NULL}}
#define UpdateItemAttributes_init_zero           {false, 0, false, ItemAttributesPartialState_init_zero, false, ItemAttributesPartialState_init_zero, false, ListChecksum_init_zero, false, ListChecksum_init_zero}
#define UpdateListAttributes_init_zero           {false, ListAttributesPartialState_init_zero, false, ListAttributesPartialState_init_zero, false, ListChecksum_init_zero, false, ListChecksum_init_zero}
#define Op_init_zero                             {false, _Op_Kind_MIN, false, Add_init_zero, false, Rem_init_zero, false, Mov_init_zero, false, UpdateItemAttributes_init_zero, false, UpdateListAttributes_init_zero}
#define OpList_init_zero                         {{{NULL}, NULL}}
#define ChangeInfo_init_zero                     {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Delta_init_zero                          {{{NULL}, NULL}, {{NULL}, NULL}, false, ChangeInfo_init_zero}
#define Merge_init_zero                          {{{NULL}, NULL}, {{NULL}, NULL}, false, ChangeInfo_init_zero}
#define ChangeSet_init_zero                      {false, _ChangeSet_Kind_MIN, false, Delta_init_zero, false, Merge_init_zero}
#define RevisionTaggedChangeSet_init_zero        {{{NULL}, NULL}, false, ChangeSet_init_zero}
#define Diff_init_zero                           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ListDump_init_zero                       {{{NULL}, NULL}, false, 0, false, ListAttributes_init_zero, false, ListChecksum_init_zero, false, ListItems_init_zero, {{NULL}, NULL}}
#define ListChanges_init_zero                    {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, ListDump_init_zero, {{NULL}, NULL}}
#define SelectedListContent_init_zero            {{{NULL}, NULL}, false, 0, false, ListAttributes_init_zero, false, ListChecksum_init_zero, false, ListItems_init_zero, false, Diff_init_zero, false, Diff_init_zero, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Diff_from_revision_tag                   1
#define Diff_ops_tag                             2
#define Diff_to_revision_tag                     3
#define OpList_ops_tag                           1
#define StringAttribute_key_tag                  1
#define StringAttribute_value_tag                2
#define StringAttributes_attribute_tag           1
#define ChangeInfo_user_tag                      1
#define ChangeInfo_timestamp_tag                 2
#define ChangeInfo_admin_tag                     3
#define ChangeInfo_undo_tag                      4
#define ChangeInfo_redo_tag                      5
#define ChangeInfo_merge_tag                     6
#define ChangeInfo_compressed_tag                7
#define ChangeInfo_migration_tag                 8
#define ClientIssue_level_tag                    1
#define ClientIssue_code_tag                     2
#define ClientIssue_repeatCount_tag              3
#define ClientResolveAction_code_tag             1
#define ClientResolveAction_initiator_tag        2
#define ContentRange_pos_tag                     1
#define ContentRange_length_tag                  2
#define DownloadFormat_codec_tag                 1
#define ListAttributes_name_tag                  1
#define ListAttributes_description_tag           2
#define ListAttributes_picture_tag               3
#define ListAttributes_collaborative_tag         4
#define ListAttributes_pl3_version_tag           5
#define ListAttributes_deleted_by_owner_tag      6
#define ListAttributes_restricted_collaborative_tag 7
#define ListAttributes_deprecated_client_id_tag  8
#define ListAttributes_public_starred_tag        9
#define ListAttributes_client_id_tag             10
#define ListChecksum_version_tag                 1
#define ListChecksum_sha1_tag                    4
#define ListItems_pos_tag                        1
#define ListItems_truncated_tag                  2
#define ListItems_items_tag                      3
#define Add_fromIndex_tag                        1
#define Add_items_tag                            2
#define Add_list_checksum_tag                    3
#define Add_addLast_tag                          4
#define Add_addFirst_tag                         5
#define Delta_base_version_tag                   1
#define Delta_ops_tag                            2
#define Delta_info_tag                           4
#define ItemAttributes_added_by_tag              1
#define ItemAttributes_timestamp_tag             2
#define ItemAttributes_message_tag               3
#define ItemAttributes_seen_tag                  4
#define ItemAttributes_download_count_tag        5
#define ItemAttributes_download_format_tag       6
#define ItemAttributes_sevendigital_id_tag       7
#define ItemAttributes_sevendigital_left_tag     8
#define ItemAttributes_seen_at_tag               9
#define ItemAttributes_public_tag                10
#define ListAttributesPartialState_values_tag    1
#define ListAttributesPartialState_no_value_tag  2
#define ListContentSelection_wantRevision_tag    1
#define ListContentSelection_wantLength_tag      2
#define ListContentSelection_wantAttributes_tag  3
#define ListContentSelection_wantChecksum_tag    4
#define ListContentSelection_wantContent_tag     5
#define ListContentSelection_contentRange_tag    6
#define ListContentSelection_wantDiff_tag        7
#define ListContentSelection_baseRevision_tag    8
#define ListContentSelection_hintRevision_tag    9
#define ListContentSelection_wantNothingIfUpToDate_tag 10
#define ListContentSelection_wantResolveAction_tag 12
#define ListContentSelection_issues_tag          13
#define ListContentSelection_resolveAction_tag   14
#define ListDump_latestRevision_tag              1
#define ListDump_length_tag                      2
#define ListDump_attributes_tag                  3
#define ListDump_checksum_tag                    4
#define ListDump_contents_tag                    5
#define ListDump_pendingDeltas_tag               7
#define Merge_base_version_tag                   1
#define Merge_merge_version_tag                  2
#define Merge_info_tag                           4
#define Mov_fromIndex_tag                        1
#define Mov_length_tag                           2
#define Mov_toIndex_tag                          3
#define Mov_list_checksum_tag                    4
#define Mov_items_checksum_tag                   5
#define Mov_uris_checksum_tag                    6
#define Rem_fromIndex_tag                        1
#define Rem_length_tag                           2
#define Rem_items_tag                            3
#define Rem_list_checksum_tag                    4
#define Rem_items_checksum_tag                   5
#define Rem_uris_checksum_tag                    6
#define Rem_itemsAsKey_tag                       7
#define SelectedListContent_revision_tag         1
#define SelectedListContent_length_tag           2
#define SelectedListContent_attributes_tag       3
#define SelectedListContent_checksum_tag         4
#define SelectedListContent_contents_tag         5
#define SelectedListContent_diff_tag             6
#define SelectedListContent_syncResult_tag       7
#define SelectedListContent_resultingRevisions_tag 8
#define SelectedListContent_multipleHeads_tag    9
#define SelectedListContent_upToDate_tag         10
#define SelectedListContent_resolveAction_tag    12
#define SelectedListContent_issues_tag           13
#define SelectedListContent_nonces_tag           14
#define ChangeSet_kind_tag                       1
#define ChangeSet_delta_tag                      2
#define ChangeSet_merge_tag                      3
#define Item_uri_tag                             1
#define Item_attributes_tag                      2
#define ItemAttributesPartialState_values_tag    1
#define ItemAttributesPartialState_no_value_tag  2
#define ListChanges_baseRevision_tag             1
#define ListChanges_deltas_tag                   2
#define ListChanges_wantResultingRevisions_tag   3
#define ListChanges_wantSyncResult_tag           4
#define ListChanges_dump_tag                     5
#define ListChanges_nonces_tag                   6
#define UpdateListAttributes_new_attributes_tag  1
#define UpdateListAttributes_old_attributes_tag  2
#define UpdateListAttributes_list_checksum_tag   3
#define UpdateListAttributes_old_attributes_checksum_tag 4
#define RevisionTaggedChangeSet_revision_tag     1
#define RevisionTaggedChangeSet_change_set_tag   2
#define UpdateItemAttributes_index_tag           1
#define UpdateItemAttributes_new_attributes_tag  2
#define UpdateItemAttributes_old_attributes_tag  3
#define UpdateItemAttributes_list_checksum_tag   4
#define UpdateItemAttributes_old_attributes_checksum_tag 5
#define Op_kind_tag                              1
#define Op_add_tag                               2
#define Op_rem_tag                               3
#define Op_mov_tag                               4
#define Op_update_item_attributes_tag            5
#define Op_update_list_attributes_tag            6

/* Struct field encoding specification for nanopb */
#define ListChecksum_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    version,           1) \
X(a, CALLBACK, OPTIONAL, BYTES,    sha1,              4)
#define ListChecksum_CALLBACK pb_default_field_callback
#define ListChecksum_DEFAULT NULL

#define DownloadFormat_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    codec,             1)
#define DownloadFormat_CALLBACK NULL
#define DownloadFormat_DEFAULT NULL

#define ListAttributes_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              1) \
X(a, CALLBACK, OPTIONAL, STRING,   description,       2) \
X(a, CALLBACK, OPTIONAL, BYTES,    picture,           3) \
X(a, STATIC,   OPTIONAL, BOOL,     collaborative,     4) \
X(a, CALLBACK, OPTIONAL, STRING,   pl3_version,       5) \
X(a, STATIC,   OPTIONAL, BOOL,     deleted_by_owner,   6) \
X(a, STATIC,   OPTIONAL, BOOL,     restricted_collaborative,   7) \
X(a, STATIC,   OPTIONAL, INT64,    deprecated_client_id,   8) \
X(a, STATIC,   OPTIONAL, BOOL,     public_starred,    9) \
X(a, CALLBACK, OPTIONAL, STRING,   client_id,        10)
#define ListAttributes_CALLBACK pb_default_field_callback
#define ListAttributes_DEFAULT NULL

#define ItemAttributes_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   added_by,          1) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         2) \
X(a, CALLBACK, OPTIONAL, STRING,   message,           3) \
X(a, STATIC,   OPTIONAL, BOOL,     seen,              4) \
X(a, STATIC,   OPTIONAL, INT64,    download_count,    5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  download_format,   6) \
X(a, CALLBACK, OPTIONAL, STRING,   sevendigital_id,   7) \
X(a, STATIC,   OPTIONAL, INT64,    sevendigital_left,   8) \
X(a, STATIC,   OPTIONAL, INT64,    seen_at,           9) \
X(a, STATIC,   OPTIONAL, BOOL,     public,           10)
#define ItemAttributes_CALLBACK pb_default_field_callback
#define ItemAttributes_DEFAULT NULL
#define ItemAttributes_download_format_MSGTYPE DownloadFormat

#define StringAttribute_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   key,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   value,             2)
#define StringAttribute_CALLBACK pb_default_field_callback
#define StringAttribute_DEFAULT NULL

#define StringAttributes_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  attribute,         1)
#define StringAttributes_CALLBACK pb_default_field_callback
#define StringAttributes_DEFAULT NULL
#define StringAttributes_attribute_MSGTYPE StringAttribute

#define ClientIssue_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    level,             1) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              2) \
X(a, STATIC,   OPTIONAL, INT32,    repeatCount,       3)
#define ClientIssue_CALLBACK NULL
#define ClientIssue_DEFAULT NULL

#define ClientResolveAction_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    code,              1) \
X(a, STATIC,   OPTIONAL, UENUM,    initiator,         2)
#define ClientResolveAction_CALLBACK NULL
#define ClientResolveAction_DEFAULT NULL

#define Item_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  attributes,        2)
#define Item_CALLBACK pb_default_field_callback
#define Item_DEFAULT NULL
#define Item_attributes_MSGTYPE ItemAttributes

#define ListItems_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    pos,               1) \
X(a, STATIC,   OPTIONAL, BOOL,     truncated,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             3)
#define ListItems_CALLBACK pb_default_field_callback
#define ListItems_DEFAULT NULL
#define ListItems_items_MSGTYPE Item

#define ContentRange_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    pos,               1) \
X(a, STATIC,   OPTIONAL, INT32,    length,            2)
#define ContentRange_CALLBACK NULL
#define ContentRange_DEFAULT NULL

#define ListContentSelection_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     wantRevision,      1) \
X(a, STATIC,   OPTIONAL, BOOL,     wantLength,        2) \
X(a, STATIC,   OPTIONAL, BOOL,     wantAttributes,    3) \
X(a, STATIC,   OPTIONAL, BOOL,     wantChecksum,      4) \
X(a, STATIC,   OPTIONAL, BOOL,     wantContent,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  contentRange,      6) \
X(a, STATIC,   OPTIONAL, BOOL,     wantDiff,          7) \
X(a, CALLBACK, OPTIONAL, BYTES,    baseRevision,      8) \
X(a, CALLBACK, OPTIONAL, BYTES,    hintRevision,      9) \
X(a, STATIC,   OPTIONAL, BOOL,     wantNothingIfUpToDate,  10) \
X(a, STATIC,   OPTIONAL, BOOL,     wantResolveAction,  12) \
X(a, CALLBACK, REPEATED, MESSAGE,  issues,           13) \
X(a, CALLBACK, REPEATED, MESSAGE,  resolveAction,    14)
#define ListContentSelection_CALLBACK pb_default_field_callback
#define ListContentSelection_DEFAULT NULL
#define ListContentSelection_contentRange_MSGTYPE ContentRange
#define ListContentSelection_issues_MSGTYPE ClientIssue
#define ListContentSelection_resolveAction_MSGTYPE ClientResolveAction

#define Add_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    fromIndex,         1) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  list_checksum,     3) \
X(a, STATIC,   OPTIONAL, BOOL,     addLast,           4) \
X(a, STATIC,   OPTIONAL, BOOL,     addFirst,          5)
#define Add_CALLBACK pb_default_field_callback
#define Add_DEFAULT NULL
#define Add_items_MSGTYPE Item
#define Add_list_checksum_MSGTYPE ListChecksum

#define Rem_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    fromIndex,         1) \
X(a, STATIC,   OPTIONAL, INT32,    length,            2) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  list_checksum,     4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  items_checksum,    5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uris_checksum,     6) \
X(a, STATIC,   OPTIONAL, BOOL,     itemsAsKey,        7)
#define Rem_CALLBACK pb_default_field_callback
#define Rem_DEFAULT NULL
#define Rem_items_MSGTYPE Item
#define Rem_list_checksum_MSGTYPE ListChecksum
#define Rem_items_checksum_MSGTYPE ListChecksum
#define Rem_uris_checksum_MSGTYPE ListChecksum

#define Mov_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    fromIndex,         1) \
X(a, STATIC,   OPTIONAL, INT32,    length,            2) \
X(a, STATIC,   OPTIONAL, INT32,    toIndex,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  list_checksum,     4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  items_checksum,    5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uris_checksum,     6)
#define Mov_CALLBACK NULL
#define Mov_DEFAULT NULL
#define Mov_list_checksum_MSGTYPE ListChecksum
#define Mov_items_checksum_MSGTYPE ListChecksum
#define Mov_uris_checksum_MSGTYPE ListChecksum

#define ItemAttributesPartialState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  values,            1) \
X(a, CALLBACK, REPEATED, UENUM,    no_value,          2)
#define ItemAttributesPartialState_CALLBACK pb_default_field_callback
#define ItemAttributesPartialState_DEFAULT NULL
#define ItemAttributesPartialState_values_MSGTYPE ItemAttributes

#define ListAttributesPartialState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  values,            1) \
X(a, CALLBACK, REPEATED, UENUM,    no_value,          2)
#define ListAttributesPartialState_CALLBACK pb_default_field_callback
#define ListAttributesPartialState_DEFAULT NULL
#define ListAttributesPartialState_values_MSGTYPE ListAttributes

#define UpdateItemAttributes_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    index,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  new_attributes,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  old_attributes,    3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  list_checksum,     4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  old_attributes_checksum,   5)
#define UpdateItemAttributes_CALLBACK NULL
#define UpdateItemAttributes_DEFAULT NULL
#define UpdateItemAttributes_new_attributes_MSGTYPE ItemAttributesPartialState
#define UpdateItemAttributes_old_attributes_MSGTYPE ItemAttributesPartialState
#define UpdateItemAttributes_list_checksum_MSGTYPE ListChecksum
#define UpdateItemAttributes_old_attributes_checksum_MSGTYPE ListChecksum

#define UpdateListAttributes_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  new_attributes,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  old_attributes,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  list_checksum,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  old_attributes_checksum,   4)
#define UpdateListAttributes_CALLBACK NULL
#define UpdateListAttributes_DEFAULT NULL
#define UpdateListAttributes_new_attributes_MSGTYPE ListAttributesPartialState
#define UpdateListAttributes_old_attributes_MSGTYPE ListAttributesPartialState
#define UpdateListAttributes_list_checksum_MSGTYPE ListChecksum
#define UpdateListAttributes_old_attributes_checksum_MSGTYPE ListChecksum

#define Op_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    kind,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  add,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rem,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mov,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  update_item_attributes,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  update_list_attributes,   6)
#define Op_CALLBACK NULL
#define Op_DEFAULT NULL
#define Op_add_MSGTYPE Add
#define Op_rem_MSGTYPE Rem
#define Op_mov_MSGTYPE Mov
#define Op_update_item_attributes_MSGTYPE UpdateItemAttributes
#define Op_update_list_attributes_MSGTYPE UpdateListAttributes

#define OpList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  ops,               1)
#define OpList_CALLBACK pb_default_field_callback
#define OpList_DEFAULT NULL
#define OpList_ops_MSGTYPE Op

#define ChangeInfo_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   user,              1) \
X(a, STATIC,   OPTIONAL, INT32,    timestamp,         2) \
X(a, STATIC,   OPTIONAL, BOOL,     admin,             3) \
X(a, STATIC,   OPTIONAL, BOOL,     undo,              4) \
X(a, STATIC,   OPTIONAL, BOOL,     redo,              5) \
X(a, STATIC,   OPTIONAL, BOOL,     merge,             6) \
X(a, STATIC,   OPTIONAL, BOOL,     compressed,        7) \
X(a, STATIC,   OPTIONAL, BOOL,     migration,         8)
#define ChangeInfo_CALLBACK pb_default_field_callback
#define ChangeInfo_DEFAULT NULL

#define Delta_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    base_version,      1) \
X(a, CALLBACK, REPEATED, MESSAGE,  ops,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,              4)
#define Delta_CALLBACK pb_default_field_callback
#define Delta_DEFAULT NULL
#define Delta_ops_MSGTYPE Op
#define Delta_info_MSGTYPE ChangeInfo

#define Merge_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    base_version,      1) \
X(a, CALLBACK, OPTIONAL, BYTES,    merge_version,     2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,              4)
#define Merge_CALLBACK pb_default_field_callback
#define Merge_DEFAULT NULL
#define Merge_info_MSGTYPE ChangeInfo

#define ChangeSet_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    kind,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  delta,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  merge,             3)
#define ChangeSet_CALLBACK NULL
#define ChangeSet_DEFAULT NULL
#define ChangeSet_delta_MSGTYPE Delta
#define ChangeSet_merge_MSGTYPE Merge

#define RevisionTaggedChangeSet_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    revision,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  change_set,        2)
#define RevisionTaggedChangeSet_CALLBACK pb_default_field_callback
#define RevisionTaggedChangeSet_DEFAULT NULL
#define RevisionTaggedChangeSet_change_set_MSGTYPE ChangeSet

#define Diff_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    from_revision,     1) \
X(a, CALLBACK, REPEATED, MESSAGE,  ops,               2) \
X(a, CALLBACK, OPTIONAL, BYTES,    to_revision,       3)
#define Diff_CALLBACK pb_default_field_callback
#define Diff_DEFAULT NULL
#define Diff_ops_MSGTYPE Op

#define ListDump_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    latestRevision,    1) \
X(a, STATIC,   OPTIONAL, INT32,    length,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  attributes,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  checksum,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  contents,          5) \
X(a, CALLBACK, REPEATED, MESSAGE,  pendingDeltas,     7)
#define ListDump_CALLBACK pb_default_field_callback
#define ListDump_DEFAULT NULL
#define ListDump_attributes_MSGTYPE ListAttributes
#define ListDump_checksum_MSGTYPE ListChecksum
#define ListDump_contents_MSGTYPE ListItems
#define ListDump_pendingDeltas_MSGTYPE Delta

#define ListChanges_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    baseRevision,      1) \
X(a, CALLBACK, REPEATED, MESSAGE,  deltas,            2) \
X(a, STATIC,   OPTIONAL, BOOL,     wantResultingRevisions,   3) \
X(a, STATIC,   OPTIONAL, BOOL,     wantSyncResult,    4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dump,              5) \
X(a, CALLBACK, REPEATED, INT32,    nonces,            6)
#define ListChanges_CALLBACK pb_default_field_callback
#define ListChanges_DEFAULT NULL
#define ListChanges_deltas_MSGTYPE Delta
#define ListChanges_dump_MSGTYPE ListDump

#define SelectedListContent_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    revision,          1) \
X(a, STATIC,   OPTIONAL, INT32,    length,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  attributes,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  checksum,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  contents,          5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  diff,              6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  syncResult,        7) \
X(a, CALLBACK, REPEATED, BYTES,    resultingRevisions,   8) \
X(a, STATIC,   OPTIONAL, BOOL,     multipleHeads,     9) \
X(a, STATIC,   OPTIONAL, BOOL,     upToDate,         10) \
X(a, CALLBACK, REPEATED, MESSAGE,  resolveAction,    12) \
X(a, CALLBACK, REPEATED, MESSAGE,  issues,           13) \
X(a, CALLBACK, REPEATED, INT32,    nonces,           14)
#define SelectedListContent_CALLBACK pb_default_field_callback
#define SelectedListContent_DEFAULT NULL
#define SelectedListContent_attributes_MSGTYPE ListAttributes
#define SelectedListContent_checksum_MSGTYPE ListChecksum
#define SelectedListContent_contents_MSGTYPE ListItems
#define SelectedListContent_diff_MSGTYPE Diff
#define SelectedListContent_syncResult_MSGTYPE Diff
#define SelectedListContent_resolveAction_MSGTYPE ClientResolveAction
#define SelectedListContent_issues_MSGTYPE ClientIssue

extern const pb_msgdesc_t ListChecksum_msg;
extern const pb_msgdesc_t DownloadFormat_msg;
extern const pb_msgdesc_t ListAttributes_msg;
extern const pb_msgdesc_t ItemAttributes_msg;
extern const pb_msgdesc_t StringAttribute_msg;
extern const pb_msgdesc_t StringAttributes_msg;
extern const pb_msgdesc_t ClientIssue_msg;
extern const pb_msgdesc_t ClientResolveAction_msg;
extern const pb_msgdesc_t Item_msg;
extern const pb_msgdesc_t ListItems_msg;
extern const pb_msgdesc_t ContentRange_msg;
extern const pb_msgdesc_t ListContentSelection_msg;
extern const pb_msgdesc_t Add_msg;
extern const pb_msgdesc_t Rem_msg;
extern const pb_msgdesc_t Mov_msg;
extern const pb_msgdesc_t ItemAttributesPartialState_msg;
extern const pb_msgdesc_t ListAttributesPartialState_msg;
extern const pb_msgdesc_t UpdateItemAttributes_msg;
extern const pb_msgdesc_t UpdateListAttributes_msg;
extern const pb_msgdesc_t Op_msg;
extern const pb_msgdesc_t OpList_msg;
extern const pb_msgdesc_t ChangeInfo_msg;
extern const pb_msgdesc_t Delta_msg;
extern const pb_msgdesc_t Merge_msg;
extern const pb_msgdesc_t ChangeSet_msg;
extern const pb_msgdesc_t RevisionTaggedChangeSet_msg;
extern const pb_msgdesc_t Diff_msg;
extern const pb_msgdesc_t ListDump_msg;
extern const pb_msgdesc_t ListChanges_msg;
extern const pb_msgdesc_t SelectedListContent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ListChecksum_fields &ListChecksum_msg
#define DownloadFormat_fields &DownloadFormat_msg
#define ListAttributes_fields &ListAttributes_msg
#define ItemAttributes_fields &ItemAttributes_msg
#define StringAttribute_fields &StringAttribute_msg
#define StringAttributes_fields &StringAttributes_msg
#define ClientIssue_fields &ClientIssue_msg
#define ClientResolveAction_fields &ClientResolveAction_msg
#define Item_fields &Item_msg
#define ListItems_fields &ListItems_msg
#define ContentRange_fields &ContentRange_msg
#define ListContentSelection_fields &ListContentSelection_msg
#define Add_fields &Add_msg
#define Rem_fields &Rem_msg
#define Mov_fields &Mov_msg
#define ItemAttributesPartialState_fields &ItemAttributesPartialState_msg
#define ListAttributesPartialState_fields &ListAttributesPartialState_msg
#define UpdateItemAttributes_fields &UpdateItemAttributes_msg
#define UpdateListAttributes_fields &UpdateListAttributes_msg
#define Op_fields &Op_msg
#define OpList_fields &OpList_msg
#define ChangeInfo_fields &ChangeInfo_msg
#define Delta_fields &Delta_msg
#define Merge_fields &Merge_msg
#define ChangeSet_fields &ChangeSet_msg
#define RevisionTaggedChangeSet_fields &RevisionTaggedChangeSet_msg
#define Diff_fields &Diff_msg
#define ListDump_fields &ListDump_msg
#define ListChanges_fields &ListChanges_msg
#define SelectedListContent_fields &SelectedListContent_msg

/* Maximum encoded size of messages (where known) */
/* ListChecksum_size depends on runtime parameters */
#define DownloadFormat_size                      2
/* ListAttributes_size depends on runtime parameters */
/* ItemAttributes_size depends on runtime parameters */
/* StringAttribute_size depends on runtime parameters */
/* StringAttributes_size depends on runtime parameters */
#define ClientIssue_size                         15
#define ClientResolveAction_size                 4
/* Item_size depends on runtime parameters */
/* ListItems_size depends on runtime parameters */
#define ContentRange_size                        22
/* ListContentSelection_size depends on runtime parameters */
/* Add_size depends on runtime parameters */
/* Rem_size depends on runtime parameters */
/* Mov_size depends on runtime parameters */
/* ItemAttributesPartialState_size depends on runtime parameters */
/* ListAttributesPartialState_size depends on runtime parameters */
/* UpdateItemAttributes_size depends on runtime parameters */
/* UpdateListAttributes_size depends on runtime parameters */
/* Op_size depends on runtime parameters */
/* OpList_size depends on runtime parameters */
/* ChangeInfo_size depends on runtime parameters */
/* Delta_size depends on runtime parameters */
/* Merge_size depends on runtime parameters */
/* ChangeSet_size depends on runtime parameters */
/* RevisionTaggedChangeSet_size depends on runtime parameters */
/* Diff_size depends on runtime parameters */
/* ListDump_size depends on runtime parameters */
/* ListChanges_size depends on runtime parameters */
/* SelectedListContent_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
