/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "presence.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PlaylistPublishedState, PlaylistPublishedState, AUTO)


PB_BIND(PlaylistTrackAddedState, PlaylistTrackAddedState, AUTO)


PB_BIND(TrackFinishedPlayingState, TrackFinishedPlayingState, AUTO)


PB_BIND(FavoriteAppAddedState, FavoriteAppAddedState, AUTO)


PB_BIND(TrackStartedPlayingState, TrackStartedPlayingState, AUTO)


PB_BIND(UriSharedState, UriSharedState, AUTO)


PB_BIND(ArtistFollowedState, ArtistFollowedState, AUTO)


PB_BIND(DeviceInformation, DeviceInformation, AUTO)


PB_BIND(GenericPresenceState, GenericPresenceState, 2)


PB_BIND(State, State, 2)


PB_BIND(StateList, StateList, AUTO)




