/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_PRESENCE_PB_H_INCLUDED
#define PB_PRESENCE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _State_Type {
    State_Type_PLAYLIST_PUBLISHED = 1,
    State_Type_PLAYLIST_TRACK_ADDED = 2,
    State_Type_TRACK_FINISHED_PLAYING = 3,
    State_Type_FAVORITE_APP_ADDED = 4,
    State_Type_TRACK_STARTED_PLAYING = 5,
    State_Type_URI_SHARED = 6,
    State_Type_ARTIST_FOLLOWED = 7,
    State_Type_GENERIC = 11
} State_Type;

/* Struct definitions */
typedef struct _DeviceInformation {
    pb_callback_t os;
    pb_callback_t type;
} DeviceInformation;

typedef struct _StateList {
    pb_callback_t states;
} StateList;

typedef struct _ArtistFollowedState {
    pb_callback_t uri;
    pb_callback_t artist_name;
    pb_callback_t artist_cover_uri;
    bool has_timestamp;
    int64_t timestamp;
} ArtistFollowedState;

typedef struct _FavoriteAppAddedState {
    pb_callback_t app_uri;
    bool has_timestamp;
    int64_t timestamp;
} FavoriteAppAddedState;

typedef struct _GenericPresenceState {
    bool has_type;
    int32_t type;
    bool has_timestamp;
    int64_t timestamp;
    pb_callback_t item_uri;
    pb_callback_t item_name;
    pb_callback_t item_image;
    pb_callback_t context_uri;
    pb_callback_t context_name;
    pb_callback_t context_image;
    pb_callback_t referrer_uri;
    pb_callback_t referrer_name;
    pb_callback_t referrer_image;
    pb_callback_t message;
    bool has_device_information;
    DeviceInformation device_information;
} GenericPresenceState;

typedef struct _PlaylistPublishedState {
    pb_callback_t uri;
    bool has_timestamp;
    int64_t timestamp;
} PlaylistPublishedState;

typedef struct _PlaylistTrackAddedState {
    pb_callback_t playlist_uri;
    pb_callback_t track_uri;
    bool has_timestamp;
    int64_t timestamp;
} PlaylistTrackAddedState;

typedef struct _TrackFinishedPlayingState {
    pb_callback_t uri;
    pb_callback_t context_uri;
    bool has_timestamp;
    int64_t timestamp;
    pb_callback_t referrer_uri;
} TrackFinishedPlayingState;

typedef struct _TrackStartedPlayingState {
    pb_callback_t uri;
    pb_callback_t context_uri;
    bool has_timestamp;
    int64_t timestamp;
    pb_callback_t referrer_uri;
} TrackStartedPlayingState;

typedef struct _UriSharedState {
    pb_callback_t uri;
    pb_callback_t message;
    bool has_timestamp;
    int64_t timestamp;
} UriSharedState;

typedef struct _State {
    bool has_timestamp;
    int64_t timestamp;
    bool has_type;
    State_Type type;
    pb_callback_t uri;
    bool has_playlist_published;
    PlaylistPublishedState playlist_published;
    bool has_playlist_track_added;
    PlaylistTrackAddedState playlist_track_added;
    bool has_track_finished_playing;
    TrackFinishedPlayingState track_finished_playing;
    bool has_favorite_app_added;
    FavoriteAppAddedState favorite_app_added;
    bool has_track_started_playing;
    TrackStartedPlayingState track_started_playing;
    bool has_uri_shared;
    UriSharedState uri_shared;
    bool has_artist_followed;
    ArtistFollowedState artist_followed;
    bool has_generic;
    GenericPresenceState generic;
} State;


/* Helper constants for enums */
#define _State_Type_MIN State_Type_PLAYLIST_PUBLISHED
#define _State_Type_MAX State_Type_GENERIC
#define _State_Type_ARRAYSIZE ((State_Type)(State_Type_GENERIC+1))


/* Initializer values for message structs */
#define PlaylistPublishedState_init_default      {{{NULL}, NULL}, false, 0}
#define PlaylistTrackAddedState_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define TrackFinishedPlayingState_init_default   {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define FavoriteAppAddedState_init_default       {{{NULL}, NULL}, false, 0}
#define TrackStartedPlayingState_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define UriSharedState_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define ArtistFollowedState_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define DeviceInformation_init_default           {{{NULL}, NULL}, {{NULL}, NULL}}
#define GenericPresenceState_init_default        {false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, DeviceInformation_init_default}
#define State_init_default                       {false, 0, false, _State_Type_MIN, {{NULL}, NULL}, false, PlaylistPublishedState_init_default, false, PlaylistTrackAddedState_init_default, false, TrackFinishedPlayingState_init_default, false, FavoriteAppAddedState_init_default, false, TrackStartedPlayingState_init_default, false, UriSharedState_init_default, false, ArtistFollowedState_init_default, false, GenericPresenceState_init_default}
#define StateList_init_default                   {{{NULL}, NULL}}
#define PlaylistPublishedState_init_zero         {{{NULL}, NULL}, false, 0}
#define PlaylistTrackAddedState_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define TrackFinishedPlayingState_init_zero      {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define FavoriteAppAddedState_init_zero          {{{NULL}, NULL}, false, 0}
#define TrackStartedPlayingState_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define UriSharedState_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define ArtistFollowedState_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define DeviceInformation_init_zero              {{{NULL}, NULL}, {{NULL}, NULL}}
#define GenericPresenceState_init_zero           {false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, DeviceInformation_init_zero}
#define State_init_zero                          {false, 0, false, _State_Type_MIN, {{NULL}, NULL}, false, PlaylistPublishedState_init_zero, false, PlaylistTrackAddedState_init_zero, false, TrackFinishedPlayingState_init_zero, false, FavoriteAppAddedState_init_zero, false, TrackStartedPlayingState_init_zero, false, UriSharedState_init_zero, false, ArtistFollowedState_init_zero, false, GenericPresenceState_init_zero}
#define StateList_init_zero                      {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceInformation_os_tag                 1
#define DeviceInformation_type_tag               2
#define StateList_states_tag                     1
#define ArtistFollowedState_uri_tag              1
#define ArtistFollowedState_artist_name_tag      2
#define ArtistFollowedState_artist_cover_uri_tag 3
#define ArtistFollowedState_timestamp_tag        4
#define FavoriteAppAddedState_app_uri_tag        1
#define FavoriteAppAddedState_timestamp_tag      2
#define GenericPresenceState_type_tag            1
#define GenericPresenceState_timestamp_tag       2
#define GenericPresenceState_item_uri_tag        3
#define GenericPresenceState_item_name_tag       4
#define GenericPresenceState_item_image_tag      5
#define GenericPresenceState_context_uri_tag     6
#define GenericPresenceState_context_name_tag    7
#define GenericPresenceState_context_image_tag   8
#define GenericPresenceState_referrer_uri_tag    9
#define GenericPresenceState_referrer_name_tag   10
#define GenericPresenceState_referrer_image_tag  11
#define GenericPresenceState_message_tag         12
#define GenericPresenceState_device_information_tag 13
#define PlaylistPublishedState_uri_tag           1
#define PlaylistPublishedState_timestamp_tag     2
#define PlaylistTrackAddedState_playlist_uri_tag 1
#define PlaylistTrackAddedState_track_uri_tag    2
#define PlaylistTrackAddedState_timestamp_tag    3
#define TrackFinishedPlayingState_uri_tag        1
#define TrackFinishedPlayingState_context_uri_tag 2
#define TrackFinishedPlayingState_timestamp_tag  3
#define TrackFinishedPlayingState_referrer_uri_tag 4
#define TrackStartedPlayingState_uri_tag         1
#define TrackStartedPlayingState_context_uri_tag 2
#define TrackStartedPlayingState_timestamp_tag   3
#define TrackStartedPlayingState_referrer_uri_tag 4
#define UriSharedState_uri_tag                   1
#define UriSharedState_message_tag               2
#define UriSharedState_timestamp_tag             3
#define State_timestamp_tag                      1
#define State_type_tag                           2
#define State_uri_tag                            3
#define State_playlist_published_tag             4
#define State_playlist_track_added_tag           5
#define State_track_finished_playing_tag         6
#define State_favorite_app_added_tag             7
#define State_track_started_playing_tag          8
#define State_uri_shared_tag                     9
#define State_artist_followed_tag                10
#define State_generic_tag                        11

/* Struct field encoding specification for nanopb */
#define PlaylistPublishedState_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               1) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         2)
#define PlaylistPublishedState_CALLBACK pb_default_field_callback
#define PlaylistPublishedState_DEFAULT NULL

#define PlaylistTrackAddedState_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   playlist_uri,      1) \
X(a, CALLBACK, OPTIONAL, STRING,   track_uri,         2) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         3)
#define PlaylistTrackAddedState_CALLBACK pb_default_field_callback
#define PlaylistTrackAddedState_DEFAULT NULL

#define TrackFinishedPlayingState_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   context_uri,       2) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         3) \
X(a, CALLBACK, OPTIONAL, STRING,   referrer_uri,      4)
#define TrackFinishedPlayingState_CALLBACK pb_default_field_callback
#define TrackFinishedPlayingState_DEFAULT NULL

#define FavoriteAppAddedState_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   app_uri,           1) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         2)
#define FavoriteAppAddedState_CALLBACK pb_default_field_callback
#define FavoriteAppAddedState_DEFAULT NULL

#define TrackStartedPlayingState_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   context_uri,       2) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         3) \
X(a, CALLBACK, OPTIONAL, STRING,   referrer_uri,      4)
#define TrackStartedPlayingState_CALLBACK pb_default_field_callback
#define TrackStartedPlayingState_DEFAULT NULL

#define UriSharedState_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   message,           2) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         3)
#define UriSharedState_CALLBACK pb_default_field_callback
#define UriSharedState_DEFAULT NULL

#define ArtistFollowedState_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   artist_name,       2) \
X(a, CALLBACK, OPTIONAL, STRING,   artist_cover_uri,   3) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         4)
#define ArtistFollowedState_CALLBACK pb_default_field_callback
#define ArtistFollowedState_DEFAULT NULL

#define DeviceInformation_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   os,                1) \
X(a, CALLBACK, OPTIONAL, STRING,   type,              2)
#define DeviceInformation_CALLBACK pb_default_field_callback
#define DeviceInformation_DEFAULT NULL

#define GenericPresenceState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    type,              1) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         2) \
X(a, CALLBACK, OPTIONAL, STRING,   item_uri,          3) \
X(a, CALLBACK, OPTIONAL, STRING,   item_name,         4) \
X(a, CALLBACK, OPTIONAL, STRING,   item_image,        5) \
X(a, CALLBACK, OPTIONAL, STRING,   context_uri,       6) \
X(a, CALLBACK, OPTIONAL, STRING,   context_name,      7) \
X(a, CALLBACK, OPTIONAL, STRING,   context_image,     8) \
X(a, CALLBACK, OPTIONAL, STRING,   referrer_uri,      9) \
X(a, CALLBACK, OPTIONAL, STRING,   referrer_name,    10) \
X(a, CALLBACK, OPTIONAL, STRING,   referrer_image,   11) \
X(a, CALLBACK, OPTIONAL, STRING,   message,          12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_information,  13)
#define GenericPresenceState_CALLBACK pb_default_field_callback
#define GenericPresenceState_DEFAULT NULL
#define GenericPresenceState_device_information_MSGTYPE DeviceInformation

#define State_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp,         1) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              2) \
X(a, CALLBACK, OPTIONAL, STRING,   uri,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  playlist_published,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  playlist_track_added,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  track_finished_playing,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  favorite_app_added,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  track_started_playing,   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uri_shared,        9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  artist_followed,  10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  generic,          11)
#define State_CALLBACK pb_default_field_callback
#define State_DEFAULT (const pb_byte_t*)"\x10\x01\x00"
#define State_playlist_published_MSGTYPE PlaylistPublishedState
#define State_playlist_track_added_MSGTYPE PlaylistTrackAddedState
#define State_track_finished_playing_MSGTYPE TrackFinishedPlayingState
#define State_favorite_app_added_MSGTYPE FavoriteAppAddedState
#define State_track_started_playing_MSGTYPE TrackStartedPlayingState
#define State_uri_shared_MSGTYPE UriSharedState
#define State_artist_followed_MSGTYPE ArtistFollowedState
#define State_generic_MSGTYPE GenericPresenceState

#define StateList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  states,            1)
#define StateList_CALLBACK pb_default_field_callback
#define StateList_DEFAULT NULL
#define StateList_states_MSGTYPE State

extern const pb_msgdesc_t PlaylistPublishedState_msg;
extern const pb_msgdesc_t PlaylistTrackAddedState_msg;
extern const pb_msgdesc_t TrackFinishedPlayingState_msg;
extern const pb_msgdesc_t FavoriteAppAddedState_msg;
extern const pb_msgdesc_t TrackStartedPlayingState_msg;
extern const pb_msgdesc_t UriSharedState_msg;
extern const pb_msgdesc_t ArtistFollowedState_msg;
extern const pb_msgdesc_t DeviceInformation_msg;
extern const pb_msgdesc_t GenericPresenceState_msg;
extern const pb_msgdesc_t State_msg;
extern const pb_msgdesc_t StateList_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PlaylistPublishedState_fields &PlaylistPublishedState_msg
#define PlaylistTrackAddedState_fields &PlaylistTrackAddedState_msg
#define TrackFinishedPlayingState_fields &TrackFinishedPlayingState_msg
#define FavoriteAppAddedState_fields &FavoriteAppAddedState_msg
#define TrackStartedPlayingState_fields &TrackStartedPlayingState_msg
#define UriSharedState_fields &UriSharedState_msg
#define ArtistFollowedState_fields &ArtistFollowedState_msg
#define DeviceInformation_fields &DeviceInformation_msg
#define GenericPresenceState_fields &GenericPresenceState_msg
#define State_fields &State_msg
#define StateList_fields &StateList_msg

/* Maximum encoded size of messages (where known) */
/* PlaylistPublishedState_size depends on runtime parameters */
/* PlaylistTrackAddedState_size depends on runtime parameters */
/* TrackFinishedPlayingState_size depends on runtime parameters */
/* FavoriteAppAddedState_size depends on runtime parameters */
/* TrackStartedPlayingState_size depends on runtime parameters */
/* UriSharedState_size depends on runtime parameters */
/* ArtistFollowedState_size depends on runtime parameters */
/* DeviceInformation_size depends on runtime parameters */
/* GenericPresenceState_size depends on runtime parameters */
/* State_size depends on runtime parameters */
/* StateList_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
